name = "hibi-sync"
main = "worker.js"
compatibility_date = "2026-06-01"

# KV: デプロイ前に `wrangler kv namespace create HIBI` を実行し、
#     出力された id を下の "PASTE_KV_NAMESPACE_ID_HERE" に貼り付ける。
[[kv_namespaces]]
binding = "HIBI"
id = "58b3d1b6df454a5d9a0391bacb937cf6"
