/* ============================================================
   zh-bank-ko.js — 듣기용 중국어 문장 뱅크 (자동 생성·손으로 편집하지 않음)
   生成元: chinese-practice-ko.html の COURSES（全24課の pool＋sentences を
   zh で重複排除）。意味（ja フィールド）は韓国語。
   再生成: COURSES を eval して {zh,py,ja,hsk} を抽出し直して上書きする。
   形式: { zh, py, ja(=한국어 뜻), hsk }
   ============================================================ */
const ZH_BANK = [{"zh":"你好。","py":"nǐ hǎo.","ja":"안녕하세요.","hsk":1},
{"zh":"您好。","py":"nín hǎo.","ja":"안녕하세요. (정중)","hsk":1},
{"zh":"你们好。","py":"nǐmen hǎo.","ja":"여러분, 안녕하세요.","hsk":1},
{"zh":"大家好。","py":"dàjiā hǎo.","ja":"여러분, 안녕하세요.","hsk":1},
{"zh":"早上好。","py":"zǎoshang hǎo.","ja":"좋은 아침입니다.","hsk":1},
{"zh":"晚上好。","py":"wǎnshang hǎo.","ja":"안녕하세요. (저녁 인사)","hsk":1},
{"zh":"老师好。","py":"lǎoshī hǎo.","ja":"선생님, 안녕하세요.","hsk":1},
{"zh":"好久不见。","py":"hǎojiǔ bújiàn.","ja":"오랜만이에요.","hsk":1},
{"zh":"你好吗？","py":"nǐ hǎo ma?","ja":"잘 지내세요?","hsk":1},
{"zh":"我很好。","py":"wǒ hěn hǎo.","ja":"잘 지내요.","hsk":1},
{"zh":"你最近怎么样？","py":"nǐ zuìjìn zěnmeyàng?","ja":"요즘 어떻게 지내세요?","hsk":1},
{"zh":"我也很好。","py":"wǒ yě hěn hǎo.","ja":"저도 잘 지내요.","hsk":1},
{"zh":"你呢？","py":"nǐ ne?","ja":"당신은요?","hsk":1},
{"zh":"谢谢。","py":"xièxie.","ja":"고마워요.","hsk":1},
{"zh":"谢谢你。","py":"xièxie nǐ.","ja":"고맙습니다.","hsk":1},
{"zh":"非常感谢。","py":"fēicháng gǎnxiè.","ja":"정말 감사합니다.","hsk":1},
{"zh":"不客气。","py":"bú kèqi.","ja":"천만에요.","hsk":1},
{"zh":"不用谢。","py":"búyòng xiè.","ja":"천만에요. (별말씀을요)","hsk":1},
{"zh":"对不起。","py":"duìbuqǐ.","ja":"죄송합니다.","hsk":1},
{"zh":"没关系。","py":"méi guānxi.","ja":"괜찮아요.","hsk":1},
{"zh":"不好意思。","py":"bù hǎoyìsi.","ja":"실례합니다. (송구스러울 때)","hsk":1},
{"zh":"请问，洗手间在哪儿？","py":"qǐngwèn, xǐshǒujiān zài nǎr?","ja":"실례지만, 화장실이 어디예요?","hsk":1},
{"zh":"我叫田中。","py":"wǒ jiào Tiánzhōng.","ja":"저는 다나카라고 합니다.","hsk":1},
{"zh":"你叫什么名字？","py":"nǐ jiào shénme míngzi?","ja":"이름이 어떻게 되세요?","hsk":1},
{"zh":"我姓王。","py":"wǒ xìng Wáng.","ja":"저는 성이 왕입니다.","hsk":1},
{"zh":"请问您贵姓？","py":"qǐngwèn nín guìxìng?","ja":"실례지만 성함이 어떻게 되세요?","hsk":1},
{"zh":"我是日本人。","py":"wǒ shì Rìběn rén.","ja":"저는 일본인입니다.","hsk":1},
{"zh":"你是哪国人？","py":"nǐ shì nǎ guó rén?","ja":"어느 나라 사람이에요?","hsk":1},
{"zh":"我是学生。","py":"wǒ shì xuésheng.","ja":"저는 학생입니다.","hsk":1},
{"zh":"我是公司职员。","py":"wǒ shì gōngsī zhíyuán.","ja":"저는 회사원입니다.","hsk":1},
{"zh":"他不是老师。","py":"tā bú shì lǎoshī.","ja":"그는 선생님이 아닙니다.","hsk":1},
{"zh":"认识你很高兴。","py":"rènshi nǐ hěn gāoxìng.","ja":"만나서 반갑습니다.","hsk":1},
{"zh":"很高兴见到你。","py":"hěn gāoxìng jiàndào nǐ.","ja":"만나서 반갑습니다.","hsk":1},
{"zh":"这是我的名片。","py":"zhè shì wǒ de míngpiàn.","ja":"이건 제 명함입니다.","hsk":1},
{"zh":"我今年二十岁。","py":"wǒ jīnnián èrshí suì.","ja":"저는 올해 스무 살입니다.","hsk":1},
{"zh":"我住在东京。","py":"wǒ zhù zài Dōngjīng.","ja":"저는 도쿄에 살아요.","hsk":1},
{"zh":"请多关照。","py":"qǐng duō guānzhào.","ja":"잘 부탁드립니다.","hsk":1},
{"zh":"再见。","py":"zàijiàn.","ja":"안녕히 가세요/계세요.","hsk":1},
{"zh":"拜拜。","py":"báibái.","ja":"바이바이.","hsk":1},
{"zh":"明天见。","py":"míngtiān jiàn.","ja":"내일 봐요.","hsk":1},
{"zh":"回头见。","py":"huítóu jiàn.","ja":"이따 봐요.","hsk":1},
{"zh":"下次见。","py":"xià cì jiàn.","ja":"다음에 봐요.","hsk":1},
{"zh":"慢走。","py":"màn zǒu.","ja":"살펴 가세요. (배웅)","hsk":1},
{"zh":"晚安。","py":"wǎn'ān.","ja":"안녕히 주무세요.","hsk":1},
{"zh":"我今年十岁。","py":"wǒ jīnnián shí suì.","ja":"저는 올해 열 살이에요.","hsk":1},
{"zh":"我有三本杂志。","py":"wǒ yǒu sān běn zázhì.","ja":"저는 잡지가 세 권 있어요.","hsk":1},
{"zh":"今天星期天。","py":"jīntiān xīngqī tiān.","ja":"오늘은 일요일이에요.","hsk":1},
{"zh":"我有一个姐姐。","py":"wǒ yǒu yí ge jiějie.","ja":"저는 누나(언니)가 한 명 있어요.","hsk":1},
{"zh":"现在八点半。","py":"xiànzài bā diǎn bàn.","ja":"지금 8시 반이에요.","hsk":1},
{"zh":"一共五块。","py":"yígòng wǔ kuài.","ja":"다 합해서 5위안이에요.","hsk":1},
{"zh":"我有一个妹妹。","py":"wǒ yǒu yí ge mèimei.","ja":"저는 여동생이 한 명 있어요.","hsk":1},
{"zh":"我有三个姐姐。","py":"wǒ yǒu sān ge jiějie.","ja":"저는 누나(언니)가 세 명 있어요.","hsk":1},
{"zh":"现在六点半。","py":"xiànzài liù diǎn bàn.","ja":"지금 6시 반이에요.","hsk":1},
{"zh":"现在四点。","py":"xiànzài sì diǎn.","ja":"지금 4시예요.","hsk":1},
{"zh":"一共三十块。","py":"yígòng sānshí kuài.","ja":"다 합해서 30위안이에요.","hsk":1},
{"zh":"我有三张地图。","py":"wǒ yǒu sān zhāng dìtú.","ja":"저는 지도가 세 장 있어요.","hsk":1},
{"zh":"我今年十五岁。","py":"wǒ jīnnián shíwǔ suì.","ja":"저는 올해 열다섯 살이에요.","hsk":1},
{"zh":"今天星期二。","py":"jīntiān xīngqī èr.","ja":"오늘은 화요일이에요.","hsk":1},
{"zh":"我有三个哥哥。","py":"wǒ yǒu sān ge gēge.","ja":"저는 형(오빠)이 세 명 있어요.","hsk":1},
{"zh":"一共十五块。","py":"yígòng shíwǔ kuài.","ja":"다 합해서 15위안이에요.","hsk":1},
{"zh":"我有两个弟弟。","py":"wǒ yǒu liǎng ge dìdi.","ja":"저는 남동생이 두 명 있어요.","hsk":1},
{"zh":"一共十块。","py":"yígòng shí kuài.","ja":"다 합해서 10위안이에요.","hsk":1},
{"zh":"今天星期五。","py":"jīntiān xīngqī wǔ.","ja":"오늘은 금요일이에요.","hsk":1},
{"zh":"我今年六岁。","py":"wǒ jīnnián liù suì.","ja":"저는 올해 여섯 살이에요.","hsk":1},
{"zh":"现在三点。","py":"xiànzài sān diǎn.","ja":"지금 3시예요.","hsk":1},
{"zh":"我有三只猫。","py":"wǒ yǒu sān zhī māo.","ja":"저는 고양이가 세 마리 있어요.","hsk":1},
{"zh":"我今年十二岁。","py":"wǒ jīnnián shí'èr suì.","ja":"저는 올해 열두 살이에요.","hsk":1},
{"zh":"我有三个妹妹。","py":"wǒ yǒu sān ge mèimei.","ja":"저는 여동생이 세 명 있어요.","hsk":1},
{"zh":"一共二十块。","py":"yígòng èrshí kuài.","ja":"다 합해서 20위안이에요.","hsk":1},
{"zh":"我有两张地图。","py":"wǒ yǒu liǎng zhāng dìtú.","ja":"저는 지도가 두 장 있어요.","hsk":1},
{"zh":"今天星期三。","py":"jīntiān xīngqī sān.","ja":"오늘은 수요일이에요.","hsk":1},
{"zh":"现在九点半。","py":"xiànzài jiǔ diǎn bàn.","ja":"지금 9시 반이에요.","hsk":1},
{"zh":"今天星期一。","py":"jīntiān xīngqī yī.","ja":"오늘은 월요일이에요.","hsk":1},
{"zh":"一共一百块。","py":"yígòng yìbǎi kuài.","ja":"다 합해서 100위안이에요.","hsk":1},
{"zh":"我有五本杂志。","py":"wǒ yǒu wǔ běn zázhì.","ja":"저는 잡지가 다섯 권 있어요.","hsk":1},
{"zh":"我今年三十五岁。","py":"wǒ jīnnián sānshíwǔ suì.","ja":"저는 올해 서른다섯 살이에요.","hsk":1},
{"zh":"现在一点半。","py":"xiànzài yì diǎn bàn.","ja":"지금 1시 반이에요.","hsk":1},
{"zh":"我有三个弟弟。","py":"wǒ yǒu sān ge dìdi.","ja":"저는 남동생이 세 명 있어요.","hsk":1},
{"zh":"我有四个问题。","py":"wǒ yǒu sì ge wèntí.","ja":"저는 문제가 네 개 있어요.","hsk":1},
{"zh":"我有一个哥哥。","py":"wǒ yǒu yí ge gēge.","ja":"저는 형(오빠)이 한 명 있어요.","hsk":1},
{"zh":"我有一本杂志。","py":"wǒ yǒu yì běn zázhì.","ja":"저는 잡지가 한 권 있어요.","hsk":1},
{"zh":"现在三点半。","py":"xiànzài sān diǎn bàn.","ja":"지금 3시 반이에요.","hsk":1},
{"zh":"我有两本书。","py":"wǒ yǒu liǎng běn shū.","ja":"저는 책이 두 권 있어요.","hsk":1},
{"zh":"现在几点？","py":"xiànzài jǐ diǎn?","ja":"지금 몇 시예요?","hsk":1},
{"zh":"今天星期几？","py":"jīntiān xīngqī jǐ?","ja":"오늘 무슨 요일이에요?","hsk":1},
{"zh":"明天是五月十五号。","py":"míngtiān shì wǔ yuè shíwǔ hào.","ja":"내일은 5월 15일이에요.","hsk":1},
{"zh":"这是我妈妈。","py":"zhè shì wǒ māma.","ja":"이쪽은 저의 어머니예요.","hsk":1},
{"zh":"她有两个孩子。","py":"tā yǒu liǎng ge háizi.","ja":"그녀에게는 아이가 두 명 있어요.","hsk":1},
{"zh":"这本书多少钱？","py":"zhè běn shū duōshao qián?","ja":"이 책은 얼마예요?","hsk":1},
{"zh":"我五点回家。","py":"wǒ wǔ diǎn huí jiā.","ja":"저는 5시에 집에 가요.","hsk":1},
{"zh":"他在公园。","py":"tā zài gōngyuán.","ja":"그는 공원에 있어요.","hsk":1},
{"zh":"我们在喝咖啡。","py":"wǒmen zài hē kāfēi.","ja":"우리는 커피를 마시고 있어요.","hsk":1},
{"zh":"我们会做饭。","py":"wǒmen huì zuò fàn.","ja":"우리는 요리를 할 수 있어요.","hsk":1},
{"zh":"她喜欢喝咖啡。","py":"tā xǐhuan hē kāfēi.","ja":"그녀는 커피 마시는 걸 좋아해요.","hsk":1},
{"zh":"我的手机在椅子上。","py":"wǒ de shǒujī zài yǐzi shàng.","ja":"제 휴대폰은 의자 위에 있어요.","hsk":1},
{"zh":"我们去食堂。","py":"wǒmen qù shítáng.","ja":"우리는 식당에 가요.","hsk":1},
{"zh":"我们想喝咖啡。","py":"wǒmen xiǎng hē kāfēi.","ja":"우리는 커피를 마시고 싶어요.","hsk":1},
{"zh":"她喜欢听音乐。","py":"tā xǐhuan tīng yīnyuè.","ja":"그녀는 음악 듣는 걸 좋아해요.","hsk":1},
{"zh":"他在看电视。","py":"tā zài kàn diànshì.","ja":"그는 TV를 보고 있어요.","hsk":1},
{"zh":"他在学中文。","py":"tā zài xué Zhōngwén.","ja":"그는 중국어를 배우고 있어요.","hsk":1},
{"zh":"我们在教室。","py":"wǒmen zài jiàoshì.","ja":"우리는 교실에 있어요.","hsk":1},
{"zh":"我会开车。","py":"wǒ huì kāichē.","ja":"저는 운전을 할 수 있어요.","hsk":1},
{"zh":"我的书在椅子上。","py":"wǒ de shū zài yǐzi shàng.","ja":"제 책은 의자 위에 있어요.","hsk":1},
{"zh":"我去公园。","py":"wǒ qù gōngyuán.","ja":"저는 공원에 가요.","hsk":1},
{"zh":"我们喜欢喝茶。","py":"wǒmen xǐhuan hē chá.","ja":"우리는 차 마시는 걸 좋아해요.","hsk":1},
{"zh":"我想听音乐。","py":"wǒ xiǎng tīng yīnyuè.","ja":"저는 음악을 듣고 싶어요.","hsk":1},
{"zh":"她在吃饭。","py":"tā zài chī fàn.","ja":"그녀는 밥을 먹고 있어요.","hsk":1},
{"zh":"我们想听音乐。","py":"wǒmen xiǎng tīng yīnyuè.","ja":"우리는 음악을 듣고 싶어요.","hsk":1},
{"zh":"我想看电视。","py":"wǒ xiǎng kàn diànshì.","ja":"저는 TV를 보고 싶어요.","hsk":1},
{"zh":"他在喝咖啡。","py":"tā zài hē kāfēi.","ja":"그는 커피를 마시고 있어요.","hsk":1},
{"zh":"我们喜欢买东西。","py":"wǒmen xǐhuan mǎi dōngxi.","ja":"우리는 쇼핑하는 걸 좋아해요.","hsk":1},
{"zh":"我们在看电视。","py":"wǒmen zài kàn diànshì.","ja":"우리는 TV를 보고 있어요.","hsk":1},
{"zh":"他去医院。","py":"tā qù yīyuàn.","ja":"그는 병원에 가요.","hsk":1},
{"zh":"她不会开车。","py":"tā bú huì kāichē.","ja":"그녀는 운전을 할 수 없어요.","hsk":1},
{"zh":"他在食堂。","py":"tā zài shítáng.","ja":"그는 식당에 있어요.","hsk":1},
{"zh":"我想买东西。","py":"wǒ xiǎng mǎi dōngxi.","ja":"저는 쇼핑을 하고 싶어요.","hsk":1},
{"zh":"我的手机在床上。","py":"wǒ de shǒujī zài chuáng shàng.","ja":"제 휴대폰은 침대 위에 있어요.","hsk":1},
{"zh":"我去学校。","py":"wǒ qù xuéxiào.","ja":"저는 학교에 가요.","hsk":1},
{"zh":"我们在商店。","py":"wǒmen zài shāngdiàn.","ja":"우리는 가게에 있어요.","hsk":1},
{"zh":"我在看书。","py":"wǒ zài kàn shū.","ja":"저는 책을 읽고 있어요.","hsk":1},
{"zh":"我的钱包在椅子上。","py":"wǒ de qiánbāo zài yǐzi shàng.","ja":"제 지갑은 의자 위에 있어요.","hsk":1},
{"zh":"她喜欢喝茶。","py":"tā xǐhuan hē chá.","ja":"그녀는 차 마시는 걸 좋아해요.","hsk":1},
{"zh":"他去图书馆。","py":"tā qù túshūguǎn.","ja":"그는 도서관에 가요.","hsk":1},
{"zh":"他会说英语。","py":"tā huì shuō Yīngyǔ.","ja":"그는 영어를 말할 수 있어요.","hsk":1},
{"zh":"我在食堂。","py":"wǒ zài shítáng.","ja":"저는 식당에 있어요.","hsk":1},
{"zh":"我们想买东西。","py":"wǒmen xiǎng mǎi dōngxi.","ja":"우리는 쇼핑을 하고 싶어요.","hsk":1},
{"zh":"她喜欢看电视。","py":"tā xǐhuan kàn diànshì.","ja":"그녀는 TV 보는 걸 좋아해요.","hsk":1},
{"zh":"我的书在桌子上。","py":"wǒ de shū zài zhuōzi shàng.","ja":"제 책은 책상 위에 있어요.","hsk":1},
{"zh":"我们想吃饭。","py":"wǒmen xiǎng chī fàn.","ja":"우리는 밥을 먹고 싶어요.","hsk":1},
{"zh":"他喜欢喝咖啡。","py":"tā xǐhuan hē kāfēi.","ja":"그는 커피 마시는 걸 좋아해요.","hsk":1},
{"zh":"我在家。","py":"wǒ zài jiā.","ja":"저는 집에 있어요.","hsk":1},
{"zh":"我喜欢喝茶。","py":"wǒ xǐhuan hē chá.","ja":"저는 차 마시는 걸 좋아해요.","hsk":1},
{"zh":"你想吃什么？","py":"nǐ xiǎng chī shénme?","ja":"뭐 먹고 싶어요?","hsk":1},
{"zh":"我会说中文。","py":"wǒ huì shuō Zhōngwén.","ja":"저는 중국어를 할 수 있어요.","hsk":1},
{"zh":"我不会开车。","py":"wǒ bú huì kāichē.","ja":"저는 운전을 못 해요.","hsk":1},
{"zh":"这是什么？","py":"zhè shì shénme?","ja":"이것은 뭐예요?","hsk":1},
{"zh":"你的书在桌子上。","py":"nǐ de shū zài zhuōzi shàng.","ja":"네 책은 책상 위에 있어.","hsk":1},
{"zh":"我们一起去吧。","py":"wǒmen yìqǐ qù ba.","ja":"같이 가요.","hsk":1},
{"zh":"刚才他买了两件衣服。","py":"gāngcái tā mǎi le liǎng jiàn yīfu.","ja":"방금 그는 옷을 두 벌 샀어요.","hsk":2},
{"zh":"他没去过北京。","py":"tā méi qù guo Běijīng.","ja":"그는 베이징에 가 본 적이 없어요.","hsk":2},
{"zh":"我们还没回家。","py":"wǒmen hái méi huí jiā.","ja":"우리는 아직 집에 안 갔어요.","hsk":2},
{"zh":"你起床了吗？","py":"nǐ qǐchuáng le ma?","ja":"일어났어요?","hsk":2},
{"zh":"我已经吃完了。","py":"wǒ yǐjīng chī wán le.","ja":"저는 이미 다 먹었어요.","hsk":2},
{"zh":"我已经知道了。","py":"wǒ yǐjīng zhīdào le.","ja":"저는 이미 알고 있어요.","hsk":2},
{"zh":"你吃饭了吗？","py":"nǐ chī fàn le ma?","ja":"밥 먹었어요?","hsk":2},
{"zh":"我已经下班了。","py":"wǒ yǐjīng xiàbān le.","ja":"저는 이미 퇴근했어요.","hsk":2},
{"zh":"我已经到了。","py":"wǒ yǐjīng dào le.","ja":"저는 이미 도착했어요.","hsk":2},
{"zh":"我们看过这部电影。","py":"wǒmen kàn guo zhè bù diànyǐng.","ja":"우리는 이 영화를 본 적이 있어요.","hsk":2},
{"zh":"他还没吃饭。","py":"tā hái méi chī fàn.","ja":"그는 아직 밥을 안 먹었어요.","hsk":2},
{"zh":"我们没看过这部电影。","py":"wǒmen méi kàn guo zhè bù diànyǐng.","ja":"우리는 이 영화를 본 적이 없어요.","hsk":2},
{"zh":"你回家了吗？","py":"nǐ huí jiā le ma?","ja":"집에 갔어요?","hsk":2},
{"zh":"今天我买了两件衣服。","py":"jīntiān wǒ mǎi le liǎng jiàn yīfu.","ja":"오늘 저는 옷을 두 벌 샀어요.","hsk":2},
{"zh":"她还没回家。","py":"tā hái méi huí jiā.","ja":"그녀는 아직 집에 안 갔어요.","hsk":2},
{"zh":"他还没起床。","py":"tā hái méi qǐchuáng.","ja":"그는 아직 안 일어났어요.","hsk":2},
{"zh":"我们还没起床。","py":"wǒmen hái méi qǐchuáng.","ja":"우리는 아직 안 일어났어요.","hsk":2},
{"zh":"她还没起床。","py":"tā hái méi qǐchuáng.","ja":"그녀는 아직 안 일어났어요.","hsk":2},
{"zh":"我们没去过北京。","py":"wǒmen méi qù guo Běijīng.","ja":"우리는 베이징에 가 본 적이 없어요.","hsk":2},
{"zh":"我还没回家。","py":"wǒ hái méi huí jiā.","ja":"저는 아직 집에 안 갔어요.","hsk":2},
{"zh":"今天她写了一封信。","py":"jīntiān tā xiě le yì fēng xìn.","ja":"오늘 그녀는 편지를 한 통 썼어요.","hsk":2},
{"zh":"我们没学过中文。","py":"wǒmen méi xué guo Zhōngwén.","ja":"우리는 중국어를 배운 적이 없어요.","hsk":2},
{"zh":"刚才我看了一本书。","py":"gāngcái wǒ kàn le yì běn shū.","ja":"방금 저는 책을 한 권 읽었어요.","hsk":2},
{"zh":"今天他买了两件衣服。","py":"jīntiān tā mǎi le liǎng jiàn yīfu.","ja":"오늘 그는 옷을 두 벌 샀어요.","hsk":2},
{"zh":"今天我喝了一杯咖啡。","py":"jīntiān wǒ hē le yì bēi kāfēi.","ja":"오늘 저는 커피를 한 잔 마셨어요.","hsk":2},
{"zh":"我还没起床。","py":"wǒ hái méi qǐchuáng.","ja":"저는 아직 안 일어났어요.","hsk":2},
{"zh":"她还没睡觉。","py":"tā hái méi shuìjiào.","ja":"그녀는 아직 안 잤어요.","hsk":2},
{"zh":"你睡觉了吗？","py":"nǐ shuìjiào le ma?","ja":"잤어요?","hsk":2},
{"zh":"今天他写了一封信。","py":"jīntiān tā xiě le yì fēng xìn.","ja":"오늘 그는 편지를 한 통 썼어요.","hsk":2},
{"zh":"他吃过日本菜。","py":"tā chī guo Rìběn cài.","ja":"그는 일본 요리를 먹어 본 적이 있어요.","hsk":2},
{"zh":"昨天他吃了三个包子。","py":"zuótiān tā chī le sān ge bāozi.","ja":"어제 그는 만두를 세 개 먹었어요.","hsk":2},
{"zh":"他去过北京。","py":"tā qù guo Běijīng.","ja":"그는 베이징에 가 본 적이 있어요.","hsk":2},
{"zh":"我们学过中文。","py":"wǒmen xué guo Zhōngwén.","ja":"우리는 중국어를 배운 적이 있어요.","hsk":2},
{"zh":"我还没睡觉。","py":"wǒ hái méi shuìjiào.","ja":"저는 아직 안 잤어요.","hsk":2},
{"zh":"他来过这里。","py":"tā lái guo zhèli.","ja":"그는 여기에 와 본 적이 있어요.","hsk":2},
{"zh":"刚才她吃了三个包子。","py":"gāngcái tā chī le sān ge bāozi.","ja":"방금 그녀는 만두를 세 개 먹었어요.","hsk":2},
{"zh":"他还没回家。","py":"tā hái méi huí jiā.","ja":"그는 아직 집에 안 갔어요.","hsk":2},
{"zh":"我没学过中文。","py":"wǒ méi xué guo Zhōngwén.","ja":"저는 중국어를 배운 적이 없어요.","hsk":2},
{"zh":"昨天我看了一本书。","py":"zuótiān wǒ kàn le yì běn shū.","ja":"어제 저는 책을 한 권 읽었어요.","hsk":2},
{"zh":"今天她看了一本书。","py":"jīntiān tā kàn le yì běn shū.","ja":"오늘 그녀는 책을 한 권 읽었어요.","hsk":2},
{"zh":"我吃了饭。","py":"wǒ chī le fàn.","ja":"저는 밥을 먹었습니다.","hsk":2},
{"zh":"我去过北京。","py":"wǒ qù guo Běijīng.","ja":"저는 베이징에 간 적이 있습니다.","hsk":2},
{"zh":"我没吃饭。","py":"wǒ méi chī fàn.","ja":"저는 밥을 먹지 않았습니다.","hsk":2},
{"zh":"我学过一点中文。","py":"wǒ xué guo yìdiǎn Zhōngwén.","ja":"중국어를 조금 배운 적이 있습니다.","hsk":2},
{"zh":"妈妈做了很多菜。","py":"māma zuò le hěn duō cài.","ja":"엄마는 요리를 많이 만들었습니다.","hsk":2},
{"zh":"你看过这部电影吗？","py":"nǐ kàn guo zhè bù diànyǐng ma?","ja":"이 영화를 본 적이 있나요?","hsk":2},
{"zh":"他正在学中文。","py":"tā zhèngzài xué Zhōngwén.","ja":"그는 중국어를 배우고 있는 중이에요.","hsk":2},
{"zh":"下个月他要去学校。","py":"xià ge yuè tā yào qù xuéxiào.","ja":"다음 달에 그는 학교에 갈 예정이에요.","hsk":2},
{"zh":"我要买东西。","py":"wǒ yào mǎi dōngxi.","ja":"저는 쇼핑을 하고 싶어요.","hsk":2},
{"zh":"我们快要下课了。","py":"wǒmen kuài yào xiàkè le.","ja":"우리는 곧 수업이 끝나요.","hsk":2},
{"zh":"明天他要去食堂。","py":"míngtiān tā yào qù shítáng.","ja":"내일 그는 식당에 갈 예정이에요.","hsk":2},
{"zh":"我要看书。","py":"wǒ yào kàn shū.","ja":"저는 책을 읽고 싶어요.","hsk":2},
{"zh":"我要喝茶。","py":"wǒ yào hē chá.","ja":"저는 차를 마시고 싶어요.","hsk":2},
{"zh":"她快要下课了。","py":"tā kuài yào xiàkè le.","ja":"그녀는 곧 수업이 끝나요.","hsk":2},
{"zh":"他快要下课了。","py":"tā kuài yào xiàkè le.","ja":"그는 곧 수업이 끝나요.","hsk":2},
{"zh":"下个月他要去家。","py":"xià ge yuè tā yào qù jiā.","ja":"다음 달에 그는 집에 갈 예정이에요.","hsk":2},
{"zh":"他快要到了。","py":"tā kuài yào dào le.","ja":"그는 곧 도착해요.","hsk":2},
{"zh":"明天我们要去图书馆。","py":"míngtiān wǒmen yào qù túshūguǎn.","ja":"내일 우리는 도서관에 갈 예정이에요.","hsk":2},
{"zh":"他正在买东西。","py":"tā zhèngzài mǎi dōngxi.","ja":"그는 쇼핑을 하고 있는 중이에요.","hsk":2},
{"zh":"我要学中文。","py":"wǒ yào xué Zhōngwén.","ja":"저는 중국어를 배우고 싶어요.","hsk":2},
{"zh":"我要吃饭。","py":"wǒ yào chī fàn.","ja":"저는 밥을 먹고 싶어요.","hsk":2},
{"zh":"我们正在买东西。","py":"wǒmen zhèngzài mǎi dōngxi.","ja":"우리는 쇼핑을 하고 있는 중이에요.","hsk":2},
{"zh":"我正在买东西。","py":"wǒ zhèngzài mǎi dōngxi.","ja":"저는 쇼핑을 하고 있는 중이에요.","hsk":2},
{"zh":"我要听音乐。","py":"wǒ yào tīng yīnyuè.","ja":"저는 음악을 듣고 싶어요.","hsk":2},
{"zh":"我要看电视。","py":"wǒ yào kàn diànshì.","ja":"저는 TV를 보고 싶어요.","hsk":2},
{"zh":"明天我要去图书馆。","py":"míngtiān wǒ yào qù túshūguǎn.","ja":"내일 저는 도서관에 갈 예정이에요.","hsk":2},
{"zh":"我们正在看书。","py":"wǒmen zhèngzài kàn shū.","ja":"우리는 책을 읽고 있는 중이에요.","hsk":2},
{"zh":"我们快要到了。","py":"wǒmen kuài yào dào le.","ja":"우리는 곧 도착해요.","hsk":2},
{"zh":"明天他要去学校。","py":"míngtiān tā yào qù xuéxiào.","ja":"내일 그는 학교에 갈 예정이에요.","hsk":2},
{"zh":"下个月我要去食堂。","py":"xià ge yuè wǒ yào qù shítáng.","ja":"다음 달에 저는 식당에 갈 예정이에요.","hsk":2},
{"zh":"他快要放假了。","py":"tā kuài yào fàngjià le.","ja":"그는 곧 방학이에요.","hsk":2},
{"zh":"下个月我要去图书馆。","py":"xià ge yuè wǒ yào qù túshūguǎn.","ja":"다음 달에 저는 도서관에 갈 예정이에요.","hsk":2},
{"zh":"他正在看电视。","py":"tā zhèngzài kàn diànshì.","ja":"그는 TV를 보고 있는 중이에요.","hsk":2},
{"zh":"明天我们要去公司。","py":"míngtiān wǒmen yào qù gōngsī.","ja":"내일 우리는 회사에 갈 예정이에요.","hsk":2},
{"zh":"我们快要毕业了。","py":"wǒmen kuài yào bìyè le.","ja":"우리는 곧 졸업해요.","hsk":2},
{"zh":"她快要毕业了。","py":"tā kuài yào bìyè le.","ja":"그녀는 곧 졸업해요.","hsk":2},
{"zh":"我们正在吃饭。","py":"wǒmen zhèngzài chī fàn.","ja":"우리는 밥을 먹고 있는 중이에요.","hsk":2},
{"zh":"明年我们要去食堂。","py":"míngnián wǒmen yào qù shítáng.","ja":"내년에 우리는 식당에 갈 예정이에요.","hsk":2},
{"zh":"下个月我要去公司。","py":"xià ge yuè wǒ yào qù gōngsī.","ja":"다음 달에 저는 회사에 갈 예정이에요.","hsk":2},
{"zh":"我要喝咖啡。","py":"wǒ yào hē kāfēi.","ja":"저는 커피를 마시고 싶어요.","hsk":2},
{"zh":"明年他要去公司。","py":"míngnián tā yào qù gōngsī.","ja":"내년에 그는 회사에 갈 예정이에요.","hsk":2},
{"zh":"她正在买东西。","py":"tā zhèngzài mǎi dōngxi.","ja":"그녀는 쇼핑을 하고 있는 중이에요.","hsk":2},
{"zh":"明年我们要去教室。","py":"míngnián wǒmen yào qù jiàoshì.","ja":"내년에 우리는 교실에 갈 예정이에요.","hsk":2},
{"zh":"我正在看书。","py":"wǒ zhèngzài kàn shū.","ja":"저는 책을 읽고 있는 중이에요.","hsk":2},
{"zh":"明天我要去公园。","py":"míngtiān wǒ yào qù gōngyuán.","ja":"내일 저는 공원에 갈 예정이에요.","hsk":2},
{"zh":"她正在学中文。","py":"tā zhèngzài xué Zhōngwén.","ja":"그녀는 중국어를 배우고 있는 중이에요.","hsk":2},
{"zh":"他正在打电话。","py":"tā zhèngzài dǎ diànhuà.","ja":"그는 지금 통화 중입니다.","hsk":2},
{"zh":"我在做作业。","py":"wǒ zài zuò zuòyè.","ja":"저는 숙제를 하고 있습니다.","hsk":2},
{"zh":"明天我要去医院。","py":"míngtiān wǒ yào qù yīyuàn.","ja":"내일 병원에 갈 예정입니다.","hsk":2},
{"zh":"我想买一件衣服。","py":"wǒ xiǎng mǎi yí jiàn yīfu.","ja":"옷을 한 벌 사고 싶습니다.","hsk":2},
{"zh":"下个月我要去中国。","py":"xià ge yuè wǒ yào qù Zhōngguó.","ja":"다음 달에 중국에 갑니다.","hsk":2},
{"zh":"他在睡觉呢。","py":"tā zài shuìjiào ne.","ja":"그는 자고 있어요.","hsk":2},
{"zh":"妈妈正在做饭。","py":"māma zhèngzài zuò fàn.","ja":"엄마는 요리를 하고 있습니다.","hsk":2},
{"zh":"我要喝一杯咖啡。","py":"wǒ yào hē yì bēi kāfēi.","ja":"커피 한 잔 마시고 싶어요.","hsk":2},
{"zh":"你在做什么呢？","py":"nǐ zài zuò shénme ne?","ja":"뭐 하고 있어요?","hsk":2},
{"zh":"我快要毕业了。","py":"wǒ kuài yào bìyè le.","ja":"저는 곧 졸업합니다.","hsk":2},
{"zh":"请给我一杯水。","py":"qǐng gěi wǒ yì bēi shuǐ.","ja":"물 한 잔 주세요.","hsk":2},
{"zh":"我比他小五岁。","py":"wǒ bǐ tā xiǎo wǔ suì.","ja":"저는 그보다 다섯 살 어려요.","hsk":2},
{"zh":"太贵了！","py":"tài guì le!","ja":"너무 비싸요!","hsk":2},
{"zh":"这里可以拍照吗？","py":"zhèli kěyǐ pāizhào ma?","ja":"여기서 사진 찍어도 돼요?","hsk":2},
{"zh":"你能等我吗？","py":"nǐ néng děng wǒ ma?","ja":"저를 기다려 줄 수 있어요?","hsk":2},
{"zh":"我妹妹比我哥哥瘦。","py":"wǒ mèimei bǐ wǒ gēge shòu.","ja":"제 여동생은 제 형(오빠)보다 말랐어요.","hsk":2},
{"zh":"这里可以抽烟吗？","py":"zhèli kěyǐ chōuyān ma?","ja":"여기서 담배 피워도 돼요?","hsk":2},
{"zh":"太棒了！","py":"tài bàng le!","ja":"최고예요!","hsk":2},
{"zh":"请给我一杯咖啡。","py":"qǐng gěi wǒ yì bēi kāfēi.","ja":"커피 한 잔 주세요.","hsk":2},
{"zh":"太好了！","py":"tài hǎo le!","ja":"잘됐다!","hsk":2},
{"zh":"我哥哥比我瘦。","py":"wǒ gēge bǐ wǒ shòu.","ja":"제 형(오빠)은 저보다 말랐어요.","hsk":2},
{"zh":"你能帮我吗？","py":"nǐ néng bāng wǒ ma?","ja":"저를 도와줄 수 있어요?","hsk":2},
{"zh":"我哥哥比他小两岁。","py":"wǒ gēge bǐ tā xiǎo liǎng suì.","ja":"제 형(오빠)은 그보다 두 살 어려요.","hsk":2},
{"zh":"这里可以停车吗？","py":"zhèli kěyǐ tíngchē ma?","ja":"여기에 주차해도 돼요?","hsk":2},
{"zh":"我比他瘦。","py":"wǒ bǐ tā shòu.","ja":"저는 그보다 말랐어요.","hsk":2},
{"zh":"你能教我吗？","py":"nǐ néng jiāo wǒ ma?","ja":"저를 가르쳐 줄 수 있어요?","hsk":2},
{"zh":"他比我妹妹忙。","py":"tā bǐ wǒ mèimei máng.","ja":"그는 제 여동생보다 바빠요.","hsk":2},
{"zh":"我妹妹比他小五岁。","py":"wǒ mèimei bǐ tā xiǎo wǔ suì.","ja":"제 여동생은 그보다 다섯 살 어려요.","hsk":2},
{"zh":"我比我哥哥忙。","py":"wǒ bǐ wǒ gēge máng.","ja":"저는 제 형(오빠)보다 바빠요.","hsk":2},
{"zh":"请给我一个面包。","py":"qǐng gěi wǒ yí ge miànbāo.","ja":"빵 한 개 주세요.","hsk":2},
{"zh":"我妹妹比我瘦。","py":"wǒ mèimei bǐ wǒ shòu.","ja":"제 여동생은 저보다 말랐어요.","hsk":2},
{"zh":"我比我哥哥小五岁。","py":"wǒ bǐ wǒ gēge xiǎo wǔ suì.","ja":"저는 제 형(오빠)보다 다섯 살 어려요.","hsk":2},
{"zh":"我比我妹妹高。","py":"wǒ bǐ wǒ mèimei gāo.","ja":"저는 제 여동생보다 키가 커요.","hsk":2},
{"zh":"我哥哥比我大五岁。","py":"wǒ gēge bǐ wǒ dà wǔ suì.","ja":"제 형(오빠)은 저보다 다섯 살 많아요.","hsk":2},
{"zh":"我哥哥比我妹妹忙。","py":"wǒ gēge bǐ wǒ mèimei máng.","ja":"제 형(오빠)은 제 여동생보다 바빠요.","hsk":2},
{"zh":"太累了！","py":"tài lèi le!","ja":"피곤해요!","hsk":2},
{"zh":"他比我大五岁。","py":"tā bǐ wǒ dà wǔ suì.","ja":"그는 저보다 다섯 살 많아요.","hsk":2},
{"zh":"我比我哥哥高。","py":"wǒ bǐ wǒ gēge gāo.","ja":"저는 제 형(오빠)보다 키가 커요.","hsk":2},
{"zh":"我比他大五岁。","py":"wǒ bǐ tā dà wǔ suì.","ja":"저는 그보다 다섯 살 많아요.","hsk":2},
{"zh":"他比我小两岁。","py":"tā bǐ wǒ xiǎo liǎng suì.","ja":"그는 저보다 두 살 어려요.","hsk":2},
{"zh":"我哥哥比他瘦。","py":"wǒ gēge bǐ tā shòu.","ja":"제 형(오빠)은 그보다 말랐어요.","hsk":2},
{"zh":"她比我大三岁。","py":"tā bǐ wǒ dà sān suì.","ja":"그녀는 저보다 세 살 많아요.","hsk":2},
{"zh":"他比我哥哥忙。","py":"tā bǐ wǒ gēge máng.","ja":"그는 제 형(오빠)보다 바빠요.","hsk":2},
{"zh":"我比他高。","py":"wǒ bǐ tā gāo.","ja":"저는 그보다 키가 커요.","hsk":2},
{"zh":"我比我哥哥小两岁。","py":"wǒ bǐ wǒ gēge xiǎo liǎng suì.","ja":"저는 제 형(오빠)보다 두 살 어려요.","hsk":2},
{"zh":"我朋友比我小两岁。","py":"wǒ péngyou bǐ wǒ xiǎo liǎng suì.","ja":"제 친구는 저보다 두 살 어려요.","hsk":2},
{"zh":"我妹妹比他瘦。","py":"wǒ mèimei bǐ tā shòu.","ja":"제 여동생은 그보다 말랐어요.","hsk":2},
{"zh":"我比我哥哥瘦。","py":"wǒ bǐ wǒ gēge shòu.","ja":"저는 제 형(오빠)보다 말랐어요.","hsk":2},
{"zh":"她比我小五岁。","py":"tā bǐ wǒ xiǎo wǔ suì.","ja":"그녀는 저보다 다섯 살 어려요.","hsk":2},
{"zh":"我妹妹比我高。","py":"wǒ mèimei bǐ wǒ gāo.","ja":"제 여동생은 저보다 키가 커요.","hsk":2},
{"zh":"他比我大两岁。","py":"tā bǐ wǒ dà liǎng suì.","ja":"그는 저보다 두 살 많습니다.","hsk":2},
{"zh":"我会做中国菜。","py":"wǒ huì zuò Zhōngguó cài.","ja":"저는 중국요리를 만들 수 있습니다.","hsk":2},
{"zh":"请慢点说。","py":"qǐng màn diǎn shuō.","ja":"천천히 말씀해 주세요.","hsk":2},
{"zh":"我也喜欢音乐。","py":"wǒ yě xǐhuan yīnyuè.","ja":"저도 음악을 좋아합니다.","hsk":2},
{"zh":"我们都是学生。","py":"wǒmen dōu shì xuéshēng.","ja":"우리는 모두 학생입니다.","hsk":2},
{"zh":"给我一杯水。","py":"gěi wǒ yì bēi shuǐ.","ja":"물 한 잔 주세요.","hsk":2},
{"zh":"如果明天下雨，我就不去。","py":"rúguǒ míngtiān xià yǔ, wǒ jiù bú qù.","ja":"만약 내일 비가 오면, 저는 안 가요.","hsk":3},
{"zh":"如果你有时间，就来我家。","py":"rúguǒ nǐ yǒu shíjiān, jiù lái wǒ jiā.","ja":"시간이 있으면, 우리 집에 오세요.","hsk":3},
{"zh":"如果累了，就早点休息。","py":"rúguǒ lèi le, jiù zǎo diǎn xiūxi.","ja":"피곤하면, 일찍 쉬세요.","hsk":3},
{"zh":"如果有问题，就给我打电话。","py":"rúguǒ yǒu wèntí, jiù gěi wǒ dǎ diànhuà.","ja":"문제가 있으면, 저에게 전화하세요.","hsk":3},
{"zh":"虽然他很累，但是还在工作。","py":"suīrán tā hěn lèi, dànshì hái zài gōngzuò.","ja":"그는 피곤하지만, 아직 일하고 있어요.","hsk":3},
{"zh":"虽然下雨，但是我们还是去了。","py":"suīrán xià yǔ, dànshì wǒmen háishi qù le.","ja":"비가 왔지만, 그래도 우리는 갔어요.","hsk":3},
{"zh":"虽然很贵，但是我很喜欢。","py":"suīrán hěn guì, dànshì wǒ hěn xǐhuan.","ja":"비싸지만, 아주 마음에 들어요.","hsk":3},
{"zh":"虽然他是中国人，但是不会做中国菜。","py":"suīrán tā shì Zhōngguó rén, dànshì bú huì zuò Zhōngguó cài.","ja":"그는 중국인이지만, 중국요리를 못 만들어요.","hsk":3},
{"zh":"因为我感冒了，所以没去上班。","py":"yīnwèi wǒ gǎnmào le, suǒyǐ méi qù shàngbān.","ja":"감기에 걸려서, 출근하지 않았어요.","hsk":3},
{"zh":"因为今天有事，所以不能来。","py":"yīnwèi jīntiān yǒu shì, suǒyǐ bù néng lái.","ja":"오늘 일이 있어서, 올 수 없어요.","hsk":3},
{"zh":"因为天气很好，所以我们去公园了。","py":"yīnwèi tiānqì hěn hǎo, suǒyǐ wǒmen qù gōngyuán le.","ja":"날씨가 좋아서, 우리는 공원에 갔어요.","hsk":3},
{"zh":"因为太忙了，所以没吃午饭。","py":"yīnwèi tài máng le, suǒyǐ méi chī wǔfàn.","ja":"너무 바빠서, 점심을 못 먹었어요.","hsk":3},
{"zh":"只要努力，就一定能成功。","py":"zhǐyào nǔlì, jiù yídìng néng chénggōng.","ja":"노력하기만 하면, 반드시 성공해요.","hsk":3},
{"zh":"只要你来，我就很高兴。","py":"zhǐyào nǐ lái, wǒ jiù hěn gāoxìng.","ja":"당신이 오기만 하면, 저는 기뻐요.","hsk":3},
{"zh":"只要有时间，我就去看你。","py":"zhǐyào yǒu shíjiān, wǒ jiù qù kàn nǐ.","ja":"시간만 있으면, 만나러 갈게요.","hsk":3},
{"zh":"只有努力，才能成功。","py":"zhǐyǒu nǔlì, cái néng chénggōng.","ja":"노력해야만, 성공할 수 있어요.","hsk":3},
{"zh":"只有多练习，才能学好中文。","py":"zhǐyǒu duō liànxí, cái néng xué hǎo Zhōngwén.","ja":"많이 연습해야만, 중국어가 늘어요.","hsk":3},
{"zh":"一下班，我就回家。","py":"yí xiàbān, wǒ jiù huí jiā.","ja":"퇴근하자마자, 저는 집에 가요.","hsk":3},
{"zh":"他一到家就睡觉了。","py":"tā yí dào jiā jiù shuìjiào le.","ja":"그는 집에 도착하자마자 잤어요.","hsk":3},
{"zh":"我一看就懂了。","py":"wǒ yí kàn jiù dǒng le.","ja":"한 번 보자마자, 바로 이해했어요.","hsk":3},
{"zh":"除了苹果，我还喜欢香蕉。","py":"chúle píngguǒ, wǒ hái xǐhuan xiāngjiāo.","ja":"사과 말고도, 저는 바나나도 좋아해요.","hsk":3},
{"zh":"除了中文，他还会说英语。","py":"chúle Zhōngwén, tā hái huì shuō Yīngyǔ.","ja":"중국어 말고도, 그는 영어도 할 수 있어요.","hsk":3},
{"zh":"除了星期天，我每天都上班。","py":"chúle xīngqītiān, wǒ měi tiān dōu shàngbān.","ja":"일요일을 빼고는, 저는 매일 출근해요.","hsk":3},
{"zh":"你应该好好休息。","py":"nǐ yīnggāi hǎohāo xiūxi.","ja":"당신은 푹 쉬어야 해요.","hsk":3},
{"zh":"你不应该这么晚睡。","py":"nǐ bù yīnggāi zhème wǎn shuì.","ja":"이렇게 늦게 자면 안 돼요.","hsk":3},
{"zh":"我们应该多运动。","py":"wǒmen yīnggāi duō yùndòng.","ja":"우리는 운동을 더 많이 해야 해요.","hsk":3},
{"zh":"我必须按时完成作业。","py":"wǒ bìxū ànshí wánchéng zuòyè.","ja":"저는 제때 숙제를 끝내야 해요.","hsk":3},
{"zh":"你必须先休息。","py":"nǐ bìxū xiān xiūxi.","ja":"당신은 먼저 쉬어야 해요.","hsk":3},
{"zh":"学生必须遵守规定。","py":"xuésheng bìxū zūnshǒu guīdìng.","ja":"학생은 규칙을 지켜야 해요.","hsk":3},
{"zh":"我得马上走了。","py":"wǒ děi mǎshàng zǒu le.","ja":"저 이제 가야겠어요.","hsk":3},
{"zh":"你得多喝水。","py":"nǐ děi duō hē shuǐ.","ja":"당신은 물을 더 많이 마셔야 해요.","hsk":3},
{"zh":"你为什么那么生气？","py":"nǐ wèishénme nàme shēngqì?","ja":"왜 그렇게 화가 났어요?","hsk":3},
{"zh":"今天为什么这么冷？","py":"jīntiān wèishénme zhème lěng?","ja":"오늘은 왜 이렇게 추워요?","hsk":3},
{"zh":"我不是不想去，而是没时间。","py":"wǒ bú shì bù xiǎng qù, ér shì méi shíjiān.","ja":"가기 싫은 게 아니라, 시간이 없어요.","hsk":3},
{"zh":"这不是茶，而是咖啡。","py":"zhè bú shì chá, ér shì kāfēi.","ja":"이건 차가 아니라, 커피예요.","hsk":3},
{"zh":"即使下雨，我也要去。","py":"jíshǐ xià yǔ, wǒ yě yào qù.","ja":"설령 비가 와도, 저는 갈 거예요.","hsk":3},
{"zh":"即使很难，我也不放弃。","py":"jíshǐ hěn nán, wǒ yě bú fàngqì.","ja":"설령 어려워도, 저는 포기하지 않아요.","hsk":3},
{"zh":"他不但会说中文，而且说得很好。","py":"tā búdàn huì shuō Zhōngwén, érqiě shuō de hěn hǎo.","ja":"그는 중국어를 할 줄 알 뿐 아니라, 잘해요.","hsk":3},
{"zh":"这家店不但便宜，而且好吃。","py":"zhè jiā diàn búdàn piányi, érqiě hǎochī.","ja":"이 가게는 쌀 뿐 아니라, 맛있어요.","hsk":3},
{"zh":"为了健康，我每天运动。","py":"wèile jiànkāng, wǒ měi tiān yùndòng.","ja":"건강을 위해, 저는 매일 운동해요.","hsk":3},
{"zh":"我一边走路一边听音乐。","py":"wǒ yìbiān zǒulù yìbiān tīng yīnyuè.","ja":"걸으면서 음악을 들어요.","hsk":3},
{"zh":"他喜欢一边喝咖啡一边看书。","py":"tā xǐhuan yìbiān hē kāfēi yìbiān kàn shū.","ja":"그는 커피를 마시면서 책 읽는 걸 좋아해요.","hsk":3},
{"zh":"别一边吃饭一边玩手机。","py":"bié yìbiān chī fàn yìbiān wán shǒujī.","ja":"밥 먹으면서 휴대폰 만지지 마.","hsk":3},
{"zh":"这个菜又便宜又好吃。","py":"zhège cài yòu piányi yòu hǎochī.","ja":"이 요리는 싸고 맛있어요.","hsk":3},
{"zh":"她又聪明又漂亮。","py":"tā yòu cōngmíng yòu piàoliang.","ja":"그녀는 똑똑하고 예뻐요.","hsk":3},
{"zh":"今天又刮风又下雨。","py":"jīntiān yòu guā fēng yòu xià yǔ.","ja":"오늘은 바람도 불고 비도 와요.","hsk":3},
{"zh":"天气越来越热了。","py":"tiānqì yuè lái yuè rè le.","ja":"날씨가 점점 더워져요.","hsk":3},
{"zh":"他的汉语越来越好了。","py":"tā de Hànyǔ yuè lái yuè hǎo le.","ja":"그의 중국어가 점점 좋아졌어요.","hsk":3},
{"zh":"我越来越喜欢这个城市。","py":"wǒ yuè lái yuè xǐhuan zhège chéngshì.","ja":"저는 이 도시가 점점 좋아져요.","hsk":3},
{"zh":"雨越来越大了。","py":"yǔ yuè lái yuè dà le.","ja":"비가 점점 거세졌어요.","hsk":3},
{"zh":"这本书越看越有意思。","py":"zhè běn shū yuè kàn yuè yǒu yìsi.","ja":"이 책은 읽을수록 재미있어요.","hsk":3},
{"zh":"他越说越快。","py":"tā yuè shuō yuè kuài.","ja":"그는 말할수록 빨라져요.","hsk":3},
{"zh":"雪越下越大。","py":"xuě yuè xià yuè dà.","ja":"눈은 내릴수록 거세졌어요.","hsk":3},
{"zh":"东西越多越好。","py":"dōngxi yuè duō yuè hǎo.","ja":"물건은 많을수록 좋아요.","hsk":3},
{"zh":"今天比昨天更冷。","py":"jīntiān bǐ zuótiān gèng lěng.","ja":"오늘은 어제보다 더 추워요.","hsk":3},
{"zh":"他比我还高。","py":"tā bǐ wǒ hái gāo.","ja":"그는 저보다 키가 더 커요.","hsk":3},
{"zh":"这个比那个更便宜。","py":"zhège bǐ nàge gèng piányi.","ja":"이건 저것보다 더 싸요.","hsk":3},
{"zh":"我比他大一点。","py":"wǒ bǐ tā dà yìdiǎn.","ja":"저는 그보다 나이가 조금 많아요.","hsk":3},
{"zh":"这条路比那条近一些。","py":"zhè tiáo lù bǐ nà tiáo jìn yìxiē.","ja":"이 길은 저 길보다 조금 가까워요.","hsk":3},
{"zh":"今天比昨天热得多。","py":"jīntiān bǐ zuótiān rè de duō.","ja":"오늘은 어제보다 훨씬 더워요.","hsk":3},
{"zh":"他的房间比我的大多了。","py":"tā de fángjiān bǐ wǒ de dà duō le.","ja":"그의 방은 제 방보다 훨씬 넓어요.","hsk":3},
{"zh":"他比我大三岁。","py":"tā bǐ wǒ dà sān suì.","ja":"그는 저보다 세 살 많아요.","hsk":3},
{"zh":"这件衣服比那件贵五十块。","py":"zhè jiàn yīfu bǐ nà jiàn guì wǔshí kuài.","ja":"이 옷은 저 옷보다 50위안 비싸요.","hsk":3},
{"zh":"我的手机跟你的一样。","py":"wǒ de shǒujī gēn nǐ de yíyàng.","ja":"제 휴대폰은 당신 것과 같아요.","hsk":3},
{"zh":"他跟他哥哥一样高。","py":"tā gēn tā gēge yíyàng gāo.","ja":"그는 자기 형(오빠)과 키가 같아요.","hsk":3},
{"zh":"这里的天气跟北京一样。","py":"zhèlǐ de tiānqì gēn Běijīng yíyàng.","ja":"여기 날씨는 베이징과 같아요.","hsk":3},
{"zh":"我的想法跟你不一样。","py":"wǒ de xiǎngfǎ gēn nǐ bù yíyàng.","ja":"제 생각은 당신과 달라요.","hsk":3},
{"zh":"这个字的读音跟那个不一样。","py":"zhège zì de dúyīn gēn nàge bù yíyàng.","ja":"이 글자의 발음은 저 글자와 달라요.","hsk":3},
{"zh":"今天没有昨天那么冷。","py":"jīntiān méiyǒu zuótiān nàme lěng.","ja":"오늘은 어제만큼 춥지 않아요.","hsk":3},
{"zh":"我没有他那么忙。","py":"wǒ méiyǒu tā nàme máng.","ja":"저는 그만큼 바쁘지 않아요.","hsk":3},
{"zh":"这个电影没有那个那么有意思。","py":"zhège diànyǐng méiyǒu nàge nàme yǒu yìsi.","ja":"이 영화는 저 영화만큼 재미있지 않아요.","hsk":3},
{"zh":"他跑得很快。","py":"tā pǎo de hěn kuài.","ja":"그는 빨리 달려요.","hsk":3},
{"zh":"你来得太早了。","py":"nǐ lái de tài zǎo le.","ja":"당신은 너무 일찍 왔어요.","hsk":3},
{"zh":"她唱歌唱得很好听。","py":"tā chàng gē chàng de hěn hǎotīng.","ja":"그녀는 노래를 아주 잘해요.","hsk":3},
{"zh":"他写汉字写得很漂亮。","py":"tā xiě Hànzì xiě de hěn piàoliang.","ja":"그는 한자를 예쁘게 써요.","hsk":3},
{"zh":"我等了你半个小时。","py":"wǒ děng le nǐ bàn ge xiǎoshí.","ja":"저는 당신을 30분 기다렸어요.","hsk":3},
{"zh":"他睡了八个小时。","py":"tā shuì le bā ge xiǎoshí.","ja":"그는 여덟 시간 잤어요.","hsk":3},
{"zh":"我们休息了十分钟。","py":"wǒmen xiūxi le shí fēnzhōng.","ja":"우리는 10분 쉬었어요.","hsk":3},
{"zh":"他每天都锻炼身体。","py":"tā měitiān dōu duànliàn shēntǐ.","ja":"그는 매일 몸을 단련해요.","hsk":3},
{"zh":"每个学生都喜欢这位老师。","py":"měi ge xuésheng dōu xǐhuan zhè wèi lǎoshī.","ja":"어느 학생이나 이 선생님을 좋아해요.","hsk":3},
{"zh":"我一边吃饭一边看电视。","py":"wǒ yìbiān chī fàn yìbiān kàn diànshì.","ja":"텔레비전을 보면서 밥을 먹어요.","hsk":3},
{"zh":"越来越冷了。","py":"yuè lái yuè lěng le.","ja":"점점 추워졌어요.","hsk":3},
{"zh":"这本书比那本有意思。","py":"zhè běn shū bǐ nà běn yǒu yìsi.","ja":"이 책은 저 책보다 재미있어요.","hsk":3},
{"zh":"越早越好。","py":"yuè zǎo yuè hǎo.","ja":"빠르면 빠를수록 좋아요.","hsk":3},
{"zh":"跟你一样，我也喜欢音乐。","py":"gēn nǐ yíyàng, wǒ yě xǐhuan yīnyuè.","ja":"당신과 마찬가지로, 저도 음악을 좋아해요.","hsk":3},
{"zh":"他汉语说得很流利。","py":"tā Hànyǔ shuō de hěn liúlì.","ja":"그는 중국어를 아주 유창하게 말해요.","hsk":3},
{"zh":"这个比那个贵一点。","py":"zhège bǐ nàge guì yìdiǎn.","ja":"이것은 저것보다 조금 비싸요.","hsk":3},
{"zh":"这件衣服没有那件那么漂亮。","py":"zhè jiàn yīfu méiyǒu nà jiàn nàme piàoliang.","ja":"이 옷은 저 옷만큼 예쁘지 않아요.","hsk":3},
{"zh":"我学了三年中文。","py":"wǒ xué le sān nián Zhōngwén.","ja":"저는 중국어를 3년 배웠어요.","hsk":3},
{"zh":"他每天都来。","py":"tā měitiān dōu lái.","ja":"그는 매일 와요.","hsk":3},
{"zh":"我把作业做完了。","py":"wǒ bǎ zuòyè zuò wán le.","ja":"저는 숙제를 다 했어요.","hsk":3},
{"zh":"他把饭吃完了。","py":"tā bǎ fàn chī wán le.","ja":"그는 밥을 다 먹었어요.","hsk":3},
{"zh":"我们把电影看完了。","py":"wǒmen bǎ diànyǐng kàn wán le.","ja":"우리는 영화를 다 봤어요.","hsk":3},
{"zh":"妈妈把饭做好了。","py":"māma bǎ fàn zuò hǎo le.","ja":"엄마는 밥을 잘 차렸어요.","hsk":3},
{"zh":"我把行李准备好了。","py":"wǒ bǎ xíngli zhǔnbèi hǎo le.","ja":"저는 짐을 다 챙겼어요.","hsk":3},
{"zh":"请把名字写好。","py":"qǐng bǎ míngzi xiě hǎo.","ja":"이름을 똑바로 써 주세요.","hsk":3},
{"zh":"请把书放在桌子上。","py":"qǐng bǎ shū fàng zài zhuōzi shàng.","ja":"책을 책상 위에 놓아 주세요.","hsk":3},
{"zh":"我把车停在门口了。","py":"wǒ bǎ chē tíng zài ménkǒu le.","ja":"저는 차를 입구에 세웠어요.","hsk":3},
{"zh":"他把名字写在本子上了。","py":"tā bǎ míngzi xiě zài běnzi shàng le.","ja":"그는 이름을 공책에 썼어요.","hsk":3},
{"zh":"别把东西放在地上。","py":"bié bǎ dōngxi fàng zài dìshàng.","ja":"물건을 바닥에 두지 마.","hsk":3},
{"zh":"我把信寄给他了。","py":"wǒ bǎ xìn jì gěi tā le.","ja":"저는 편지를 그에게 부쳤어요.","hsk":3},
{"zh":"请把这本书还给图书馆。","py":"qǐng bǎ zhè běn shū huán gěi túshūguǎn.","ja":"이 책을 도서관에 반납해 주세요.","hsk":3},
{"zh":"他把礼物送给妈妈了。","py":"tā bǎ lǐwù sòng gěi māma le.","ja":"그는 선물을 엄마에게 줬어요.","hsk":3},
{"zh":"我把钱交给老师了。","py":"wǒ bǎ qián jiāo gěi lǎoshī le.","ja":"저는 돈을 선생님께 냈어요.","hsk":3},
{"zh":"他把杯子打破了。","py":"tā bǎ bēizi dǎ pò le.","ja":"그는 컵을 깨뜨렸어요.","hsk":3},
{"zh":"我不小心把手机弄坏了。","py":"wǒ bù xiǎoxīn bǎ shǒujī nòng huài le.","ja":"저는 실수로 휴대폰을 망가뜨렸어요.","hsk":3},
{"zh":"弟弟把衣服弄脏了。","py":"dìdi bǎ yīfu nòng zāng le.","ja":"남동생은 옷을 더럽혔어요.","hsk":3},
{"zh":"请把房间打扫干净。","py":"qǐng bǎ fángjiān dǎsǎo gānjìng.","ja":"방을 깨끗이 청소해 주세요.","hsk":3},
{"zh":"我把桌子擦干净了。","py":"wǒ bǎ zhuōzi cā gānjìng le.","ja":"저는 책상을 닦아서 깨끗하게 했어요.","hsk":3},
{"zh":"请把话说清楚。","py":"qǐng bǎ huà shuō qīngchu.","ja":"말을 분명하게 해 주세요.","hsk":3},
{"zh":"请把门关上。","py":"qǐng bǎ mén guān shàng.","ja":"문을 닫아 주세요.","hsk":3},
{"zh":"你把窗户打开吧。","py":"nǐ bǎ chuānghu dǎ kāi ba.","ja":"창문 좀 열어 줘.","hsk":3},
{"zh":"请把灯关上。","py":"qǐng bǎ dēng guān shàng.","ja":"불 좀 꺼 주세요.","hsk":3},
{"zh":"他把箱子打开了。","py":"tā bǎ xiāngzi dǎ kāi le.","ja":"그는 상자를 열었어요.","hsk":3},
{"zh":"他把车开走了。","py":"tā bǎ chē kāi zǒu le.","ja":"그는 차를 운전해서 가 버렸어요.","hsk":3},
{"zh":"请把椅子搬过来。","py":"qǐng bǎ yǐzi bān guò lái.","ja":"의자를 옮겨 와 주세요.","hsk":3},
{"zh":"把垃圾扔出去。","py":"bǎ lājī rēng chū qù.","ja":"쓰레기를 내다 버려.","hsk":3},
{"zh":"请把这些书收起来。","py":"qǐng bǎ zhèxiē shū shōu qǐlái.","ja":"이 책들을 정리해 주세요.","hsk":3},
{"zh":"请把这句话翻译成中文。","py":"qǐng bǎ zhè jù huà fānyì chéng Zhōngwén.","ja":"이 문장을 중국어로 번역해 주세요.","hsk":3},
{"zh":"我把美元换成人民币了。","py":"wǒ bǎ měiyuán huàn chéng rénmínbì le.","ja":"저는 달러를 인민폐로 환전했어요.","hsk":3},
{"zh":"老师把课文翻译成英文了。","py":"lǎoshī bǎ kèwén fānyì chéng Yīngwén le.","ja":"선생님은 본문을 영어로 번역했어요.","hsk":3},
{"zh":"我把这件事告诉他了。","py":"wǒ bǎ zhè jiàn shì gàosu tā le.","ja":"저는 이 일을 그에게 말했어요.","hsk":3},
{"zh":"请把你的电话号码告诉我。","py":"qǐng bǎ nǐ de diànhuà hàomǎ gàosu wǒ.","ja":"당신의 전화번호를 알려 주세요.","hsk":3},
{"zh":"别把这件事告诉别人。","py":"bié bǎ zhè jiàn shì gàosu biérén.","ja":"이 일을 남에게 말하지 마.","hsk":3},
{"zh":"我没把作业带来。","py":"wǒ méi bǎ zuòyè dài lái.","ja":"저는 숙제를 안 가져왔어요.","hsk":3},
{"zh":"别把垃圾扔在这里。","py":"bié bǎ lājī rēng zài zhèlǐ.","ja":"쓰레기를 여기에 버리지 마.","hsk":3},
{"zh":"请把灯关掉。","py":"qǐng bǎ dēng guān diào.","ja":"불 좀 꺼 주세요.","hsk":3},
{"zh":"他把那杯咖啡喝掉了。","py":"tā bǎ nà bēi kāfēi hē diào le.","ja":"그는 그 커피를 다 마셔 버렸어요.","hsk":3},
{"zh":"我把钥匙忘在家里了。","py":"wǒ bǎ yàoshi wàng zài jiā li le.","ja":"저는 열쇠를 집에 두고 왔어요.","hsk":3},
{"zh":"请把书放进书包里。","py":"qǐng bǎ shū fàng jìn shūbāo li.","ja":"책을 가방에 넣어 주세요.","hsk":3},
{"zh":"我看见你了。","py":"wǒ kàn jiàn nǐ le.","ja":"당신이 보였어요.","hsk":3},
{"zh":"我听见有人叫我。","py":"wǒ tīng jiàn yǒu rén jiào wǒ.","ja":"누군가 나를 부르는 게 들렸어요.","hsk":3},
{"zh":"我没看见他。","py":"wǒ méi kàn jiàn tā.","ja":"저는 그를 못 봤어요.","hsk":3},
{"zh":"这次我听懂了。","py":"zhè cì wǒ tīng dǒng le.","ja":"이번에는 알아들었어요.","hsk":3},
{"zh":"我看懂了这本书。","py":"wǒ kàn dǒng le zhè běn shū.","ja":"저는 이 책을 읽고 이해했어요.","hsk":3},
{"zh":"老师说的话我没听懂。","py":"lǎoshī shuō de huà wǒ méi tīng dǒng.","ja":"선생님의 말을 알아듣지 못했어요.","hsk":3},
{"zh":"我没找到那本书。","py":"wǒ méi zhǎo dào nà běn shū.","ja":"그 책을 못 찾았어요.","hsk":3},
{"zh":"我买到票了。","py":"wǒ mǎi dào piào le.","ja":"저는 표를 살 수 있었어요.","hsk":3},
{"zh":"我收到你的信了。","py":"wǒ shōu dào nǐ de xìn le.","ja":"당신의 편지를 받았어요.","hsk":3},
{"zh":"我想到了一个好主意。","py":"wǒ xiǎng dào le yí ge hǎo zhǔyi.","ja":"좋은 생각이 떠올랐어요.","hsk":3},
{"zh":"我没等到他。","py":"wǒ méi děng dào tā.","ja":"저는 그를 기다렸지만 만나지 못했어요.","hsk":3},
{"zh":"这个字我写错了。","py":"zhège zì wǒ xiě cuò le.","ja":"이 글자를 잘못 썼어요.","hsk":3},
{"zh":"对不起，我说错了。","py":"duìbuqǐ, wǒ shuō cuò le.","ja":"미안해요, 잘못 말했어요.","hsk":3},
{"zh":"我看错人了。","py":"wǒ kàn cuò rén le.","ja":"사람을 잘못 봤어요.","hsk":3},
{"zh":"你打错电话了。","py":"nǐ dǎ cuò diànhuà le.","ja":"전화 잘못 거셨어요.","hsk":3},
{"zh":"我吃完了。","py":"wǒ chī wán le.","ja":"다 먹었어요.","hsk":3},
{"zh":"钱用完了。","py":"qián yòng wán le.","ja":"돈을 다 썼어요.","hsk":3},
{"zh":"我看完这本书了。","py":"wǒ kàn wán zhè běn shū le.","ja":"이 책을 다 읽었어요.","hsk":3},
{"zh":"他做完作业了。","py":"tā zuò wán zuòyè le.","ja":"그는 숙제를 다 했어요.","hsk":3},
{"zh":"你猜对了！","py":"nǐ cāi duì le!","ja":"맞혔어요!","hsk":3},
{"zh":"这道题我做对了。","py":"zhè dào tí wǒ zuò duì le.","ja":"이 문제는 맞혔어요.","hsk":3},
{"zh":"你说对了。","py":"nǐ shuō duì le.","ja":"당신 말이 맞아요.","hsk":3},
{"zh":"我准备好了。","py":"wǒ zhǔnbèi hǎo le.","ja":"준비가 됐어요.","hsk":3},
{"zh":"妈妈做好饭了。","py":"māma zuò hǎo fàn le.","ja":"엄마는 밥을 다 차렸어요.","hsk":3},
{"zh":"我写好作业了。","py":"wǒ xiě hǎo zuòyè le.","ja":"숙제를 다 써냈어요.","hsk":3},
{"zh":"我没听清楚。","py":"wǒ méi tīng qīngchu.","ja":"제대로 알아듣지 못했어요.","hsk":3},
{"zh":"我看清楚了黑板上的字。","py":"wǒ kàn qīngchu le hēibǎn shàng de zì.","ja":"칠판의 글자가 또렷이 보였어요.","hsk":3},
{"zh":"请你说清楚。","py":"qǐng nǐ shuō qīngchu.","ja":"분명하게 말해 주세요.","hsk":3},
{"zh":"这件事我记住了。","py":"zhè jiàn shì wǒ jì zhù le.","ja":"이 일을 외웠어요.","hsk":3},
{"zh":"他抓住了我的手。","py":"tā zhuā zhù le wǒ de shǒu.","ja":"그는 제 손을 잡았어요.","hsk":3},
{"zh":"站住，别动！","py":"zhàn zhù, bié dòng!","ja":"멈춰, 움직이지 마!","hsk":3},
{"zh":"这些单词我记不住。","py":"zhèxiē dāncí wǒ jì bú zhù.","ja":"이 단어들이 안 외워져요.","hsk":3},
{"zh":"我学会游泳了。","py":"wǒ xué huì yóuyǒng le.","ja":"저는 수영을 할 수 있게 됐어요.","hsk":3},
{"zh":"这个动作我学不会。","py":"zhège dòngzuò wǒ xué bú huì.","ja":"이 동작은 아무리 해도 안 돼요.","hsk":3},
{"zh":"我吃饱了。","py":"wǒ chī bǎo le.","ja":"배불리 먹었어요.","hsk":3},
{"zh":"他昨天喝醉了。","py":"tā zuótiān hē zuì le.","ja":"그는 어제 취했어요.","hsk":3},
{"zh":"我把衣服洗干净了。","py":"wǒ bǎ yīfu xǐ gānjìng le.","ja":"저는 옷을 빨아서 깨끗하게 했어요.","hsk":3},
{"zh":"请把手洗干净。","py":"qǐng bǎ shǒu xǐ gānjìng.","ja":"손을 깨끗이 씻으세요.","hsk":3},
{"zh":"这个门我打不开。","py":"zhège mén wǒ dǎ bù kāi.","ja":"이 문이 아무리 해도 안 열려요.","hsk":3},
{"zh":"我终于打开了这个箱子。","py":"wǒ zhōngyú dǎ kāi le zhège xiāngzi.","ja":"저는 드디어 이 상자를 열었어요.","hsk":3},
{"zh":"我看见了你。","py":"wǒ kàn jiàn le nǐ.","ja":"당신이 보였어요.","hsk":3},
{"zh":"我听懂了。","py":"wǒ tīng dǒng le.","ja":"알아들었어요.","hsk":3},
{"zh":"这个汉字我写错了。","py":"zhège hànzì wǒ xiě cuò le.","ja":"이 한자를 잘못 썼어요.","hsk":3},
{"zh":"他还没做好。","py":"tā hái méi zuò hǎo.","ja":"그는 아직 다 만들지 못했어요.","hsk":3},
{"zh":"他唱歌唱得很好。","py":"tā chàng gē chàng de hěn hǎo.","ja":"그는 노래를 잘해요.","hsk":3},
{"zh":"他写字写得很漂亮。","py":"tā xiě zì xiě de hěn piàoliang.","ja":"그는 글씨를 예쁘게 써요.","hsk":3},
{"zh":"今天我起得很晚。","py":"jīntiān wǒ qǐ de hěn wǎn.","ja":"오늘 저는 늦게 일어났어요.","hsk":3},
{"zh":"我跑得比他快。","py":"wǒ pǎo de bǐ tā kuài.","ja":"저는 그보다 빨리 달릴 수 있어요.","hsk":3},
{"zh":"他这次考得不太好。","py":"tā zhè cì kǎo de bú tài hǎo.","ja":"그는 이번에 시험을 별로 못 봤어요.","hsk":3},
{"zh":"你昨天睡得怎么样？","py":"nǐ zuótiān shuì de zěnmeyàng?","ja":"어제 잘 잤어요?","hsk":3},
{"zh":"他高兴得跳了起来。","py":"tā gāoxìng de tiào le qǐlái.","ja":"그는 기뻐서 펄쩍 뛰어올랐어요.","hsk":3},
{"zh":"我累得走不动了。","py":"wǒ lèi de zǒu bu dòng le.","ja":"저는 피곤해서 걸을 수 없게 됐어요.","hsk":3},
{"zh":"他气得说不出话来。","py":"tā qì de shuō bu chū huà lái.","ja":"그는 화가 나서 말이 안 나왔어요.","hsk":3},
{"zh":"大家笑得肚子都疼了。","py":"dàjiā xiào de dùzi dōu téng le.","ja":"다들 웃겨서 배가 아팠어요.","hsk":3},
{"zh":"这个菜辣得我吃不了。","py":"zhège cài là de wǒ chī bu liǎo.","ja":"이 요리는 너무 매워서 못 먹겠어요.","hsk":3},
{"zh":"你快进来吧。","py":"nǐ kuài jìnlái ba.","ja":"빨리 들어와.","hsk":3},
{"zh":"我们出去吧。","py":"wǒmen chūqù ba.","ja":"나가자.","hsk":3},
{"zh":"请上来。","py":"qǐng shànglái.","ja":"올라오세요.","hsk":3},
{"zh":"你下来。","py":"nǐ xiàlái.","ja":"내려와.","hsk":3},
{"zh":"我们回去吧。","py":"wǒmen huíqù ba.","ja":"돌아가자.","hsk":3},
{"zh":"他从外面走进来了。","py":"tā cóng wàimiàn zǒu jìnlái le.","ja":"그는 밖에서 걸어 들어왔어요.","hsk":3},
{"zh":"你拿出来给我看看。","py":"nǐ ná chūlái gěi wǒ kàn kan.","ja":"꺼내서 좀 보여 줘.","hsk":3},
{"zh":"他从屋里跑出去了。","py":"tā cóng wū li pǎo chūqù le.","ja":"그는 방에서 뛰어나갔어요.","hsk":3},
{"zh":"他从楼上走下来了。","py":"tā cóng lóushàng zǒu xiàlái le.","ja":"그는 위층에서 걸어 내려왔어요.","hsk":3},
{"zh":"小鸟飞回来了。","py":"xiǎo niǎo fēi huílái le.","ja":"작은 새가 날아 돌아왔어요.","hsk":3},
{"zh":"请你站起来。","py":"qǐng nǐ zhàn qǐlái.","ja":"일어서 주세요.","hsk":3},
{"zh":"老师走进教室来了。","py":"lǎoshī zǒu jìn jiàoshì lái le.","ja":"선생님이 교실로 들어오셨어요.","hsk":3},
{"zh":"他跑出门去了。","py":"tā pǎo chū mén qù le.","ja":"그는 문으로 뛰어나갔어요.","hsk":3},
{"zh":"我把车开回家来了。","py":"wǒ bǎ chē kāi huí jiā lái le.","ja":"저는 차를 운전해서 집으로 돌아왔어요.","hsk":3},
{"zh":"把书拿过来。","py":"bǎ shū ná guòlái.","ja":"책을 가져와.","hsk":3},
{"zh":"请把椅子搬上去。","py":"qǐng bǎ yǐzi bān shàngqù.","ja":"의자를 위로 옮겨 주세요.","hsk":3},
{"zh":"把这些东西收起来。","py":"bǎ zhèxiē dōngxi shōu qǐlái.","ja":"이 물건들을 치워.","hsk":3},
{"zh":"你试试这件衣服吧。","py":"nǐ shìshi zhè jiàn yīfu ba.","ja":"이 옷을 한번 입어 봐.","hsk":3},
{"zh":"让我想想。","py":"ràng wǒ xiǎngxiang.","ja":"좀 생각하게 해 줘.","hsk":3},
{"zh":"我们休息休息吧。","py":"wǒmen xiūxi xiūxi ba.","ja":"좀 쉬자.","hsk":3},
{"zh":"他终于醒过来了。","py":"tā zhōngyú xǐng guòlái le.","ja":"그는 드디어 의식을 되찾았어요.","hsk":3},
{"zh":"我想起来了。","py":"wǒ xiǎng qǐlái le.","ja":"생각났어요.","hsk":3},
{"zh":"你要坚持下去。","py":"nǐ yào jiānchí xiàqù.","ja":"당신은 계속해야 해요.","hsk":3},
{"zh":"你听得见吗？","py":"nǐ tīng de jiàn ma?","ja":"들려요?","hsk":3},
{"zh":"黑板上的字我看不见。","py":"hēibǎn shàng de zì wǒ kàn bu jiàn.","ja":"칠판의 글자가 안 보여요.","hsk":3},
{"zh":"这么多菜我吃不完。","py":"zhème duō cài wǒ chī bu wán.","ja":"이렇게 많은 요리는 다 못 먹어요.","hsk":3},
{"zh":"走出去。","py":"zǒu chūqù.","ja":"밖으로 나간다.","hsk":3},
{"zh":"我应该早点睡觉。","py":"wǒ yīnggāi zǎo diǎn shuìjiào.","ja":"저는 일찍 자야 해요.","hsk":3},
{"zh":"你应该多喝水。","py":"nǐ yīnggāi duō hē shuǐ.","ja":"당신은 물을 더 많이 마셔야 해요.","hsk":3},
{"zh":"你最好早点睡觉。","py":"nǐ zuìhǎo zǎo diǎn shuìjiào.","ja":"일찍 자는 게 좋아요.","hsk":3},
{"zh":"你最好别去那里。","py":"nǐ zuìhǎo bié qù nàli.","ja":"거기엔 안 가는 게 좋아요.","hsk":3},
{"zh":"我得走了。","py":"wǒ děi zǒu le.","ja":"저 이제 가야겠어요.","hsk":3},
{"zh":"明天你必须来。","py":"míngtiān nǐ bìxū lái.","ja":"내일 당신은 꼭 와야 해요.","hsk":3},
{"zh":"学生必须遵守规则。","py":"xuésheng bìxū zūnshǒu guīzé.","ja":"학생은 규칙을 지켜야 해요.","hsk":3},
{"zh":"你要注意身体。","py":"nǐ yào zhùyì shēntǐ.","ja":"몸 조심하세요.","hsk":3},
{"zh":"这里可以照相吗？","py":"zhèlǐ kěyǐ zhàoxiàng ma?","ja":"여기서 사진 찍어도 돼요?","hsk":3},
{"zh":"你能帮我一下吗？","py":"nǐ néng bāng wǒ yíxià ma?","ja":"좀 도와줄 수 있어요?","hsk":3},
{"zh":"我不会游泳。","py":"wǒ bú huì yóuyǒng.","ja":"저는 수영을 못해요.","hsk":3},
{"zh":"你可以坐这儿。","py":"nǐ kěyǐ zuò zhèr.","ja":"여기 앉아도 돼요.","hsk":3},
{"zh":"我想去中国旅游。","py":"wǒ xiǎng qù Zhōngguó lǚyóu.","ja":"저는 중국으로 여행 가고 싶어요.","hsk":3},
{"zh":"我愿意帮助你。","py":"wǒ yuànyì bāngzhù nǐ.","ja":"저는 기꺼이 당신을 도울게요.","hsk":3},
{"zh":"我不敢一个人去。","py":"wǒ bù gǎn yí ge rén qù.","ja":"저는 혼자 갈 엄두가 안 나요.","hsk":3},
{"zh":"他不肯告诉我。","py":"tā bù kěn gàosu wǒ.","ja":"그는 한사코 알려 주지 않아요.","hsk":3},
{"zh":"妈妈让我做作业。","py":"māma ràng wǒ zuò zuòyè.","ja":"엄마는 저에게 숙제를 시켜요.","hsk":3},
{"zh":"老师叫我们安静。","py":"lǎoshī jiào wǒmen ānjìng.","ja":"선생님은 우리를 조용히 시켰어요.","hsk":3},
{"zh":"这件事让我很难过。","py":"zhè jiàn shì ràng wǒ hěn nánguò.","ja":"이 일은 저를 슬프게 했어요.","hsk":3},
{"zh":"这部电影使我很感动。","py":"zhè bù diànyǐng shǐ wǒ hěn gǎndòng.","ja":"이 영화는 저를 깊이 감동시켰어요.","hsk":3},
{"zh":"老板不让我们早走。","py":"lǎobǎn bú ràng wǒmen zǎo zǒu.","ja":"사장님은 우리를 일찍 못 가게 해요.","hsk":3},
{"zh":"他可能已经走了。","py":"tā kěnéng yǐjīng zǒu le.","ja":"그는 이미 갔을지도 몰라요.","hsk":3},
{"zh":"他大概不知道这件事。","py":"tā dàgài bù zhīdào zhè jiàn shì.","ja":"그는 아마 이 일을 모를 거예요.","hsk":3},
{"zh":"也许明天会下雨。","py":"yěxǔ míngtiān huì xià yǔ.","ja":"어쩌면 내일 비가 올지도 몰라요.","hsk":3},
{"zh":"他一定会成功。","py":"tā yídìng huì chénggōng.","ja":"그는 분명 성공할 거예요.","hsk":3},
{"zh":"这件事他肯定知道。","py":"zhè jiàn shì tā kěndìng zhīdào.","ja":"이 일을 그는 틀림없이 알고 있어요.","hsk":3},
{"zh":"听说他下个月结婚。","py":"tīngshuō tā xià ge yuè jiéhūn.","ja":"그는 다음 달에 결혼한대요.","hsk":3},
{"zh":"据说那家餐厅很有名。","py":"jùshuō nà jiā cāntīng hěn yǒumíng.","ja":"그 식당은 유명하대요.","hsk":3},
{"zh":"看起来今天要下雨。","py":"kàn qǐlái jīntiān yào xià yǔ.","ja":"오늘 비가 올 것 같아요.","hsk":3},
{"zh":"他看上去很累。","py":"tā kàn shàngqù hěn lèi.","ja":"그는 피곤해 보여요.","hsk":3},
{"zh":"说不定他不来了。","py":"shuōbudìng tā bù lái le.","ja":"어쩌면 그는 안 올지도 몰라요.","hsk":3},
{"zh":"我以为你不来了。","py":"wǒ yǐwéi nǐ bù lái le.","ja":"저는 당신이 안 올 줄 알았어요.","hsk":3},
{"zh":"我认为他是对的。","py":"wǒ rènwéi tā shì duì de.","ja":"저는 그가 옳다고 생각해요.","hsk":3},
{"zh":"我觉得这个主意不错。","py":"wǒ juéde zhège zhǔyi búcuò.","ja":"이 아이디어 괜찮은 것 같아요.","hsk":3},
{"zh":"别担心，没关系。","py":"bié dānxīn, méi guānxi.","ja":"걱정 마요, 괜찮아요.","hsk":3},
{"zh":"上课的时候不要说话。","py":"shàngkè de shíhou búyào shuōhuà.","ja":"수업 중에는 말하지 마세요.","hsk":3},
{"zh":"别哭了。","py":"bié kū le.","ja":"이제 그만 울어.","hsk":3},
{"zh":"我对中国文化感兴趣。","py":"wǒ duì Zhōngguó wénhuà gǎn xìngqù.","ja":"저는 중국 문화에 관심이 있어요.","hsk":3},
{"zh":"他对历史很感兴趣。","py":"tā duì lìshǐ hěn gǎn xìngqù.","ja":"그는 역사에 관심이 아주 많아요.","hsk":3},
{"zh":"他终于来了。","py":"tā zhōngyú lái le.","ja":"드디어 그가 왔어요.","hsk":3},
{"zh":"不管多忙，我都会给你打电话。","py":"bùguǎn duō máng, wǒ dōu huì gěi nǐ dǎ diànhuà.","ja":"아무리 바빠도, 전화할게요.","hsk":4},
{"zh":"不管谁来，我都欢迎。","py":"bùguǎn shéi lái, wǒ dōu huānyíng.","ja":"누가 오든, 저는 환영해요.","hsk":4},
{"zh":"不管你说什么，我都不会改变主意。","py":"bùguǎn nǐ shuō shénme, wǒ dōu bú huì gǎibiàn zhǔyi.","ja":"당신이 무슨 말을 해도, 저는 생각을 바꾸지 않아요.","hsk":4},
{"zh":"无论遇到什么困难，他都不放弃。","py":"wúlùn yùdào shénme kùnnan, tā dōu bú fàngqì.","ja":"어떤 어려움을 만나도, 그는 포기하지 않아요.","hsk":4},
{"zh":"无论你怎么说，我都不信。","py":"wúlùn nǐ zěnme shuō, wǒ dōu bú xìn.","ja":"당신이 뭐라고 해도, 저는 안 믿어요.","hsk":4},
{"zh":"无论多累，他都坚持锻炼。","py":"wúlùn duō lèi, tā dōu jiānchí duànliàn.","ja":"아무리 피곤해도, 그는 운동을 계속해요.","hsk":4},
{"zh":"不论结果如何，我都不后悔。","py":"búlùn jiéguǒ rúhé, wǒ dōu bù hòuhuǐ.","ja":"결과가 어떻든, 저는 후회하지 않아요.","hsk":4},
{"zh":"不论价格多高，他都要买。","py":"búlùn jiàgé duō gāo, tā dōu yào mǎi.","ja":"값이 아무리 비싸도, 그는 사요.","hsk":4},
{"zh":"不管你同意还是反对，我都要去。","py":"bùguǎn nǐ tóngyì háishi fǎnduì, wǒ dōu yào qù.","ja":"당신이 찬성하든 반대하든, 저는 갈 거예요.","hsk":4},
{"zh":"无论是大人还是孩子，都喜欢这部电影。","py":"wúlùn shì dàren háishi háizi, dōu xǐhuan zhè bù diànyǐng.","ja":"어른이든 아이든, 다 이 영화를 좋아해요.","hsk":4},
{"zh":"不管刮风还是下雨，他都去上班。","py":"bùguǎn guā fēng háishi xià yǔ, tā dōu qù shàngbān.","ja":"바람이 불든 비가 오든, 그는 출근해요.","hsk":4},
{"zh":"即使下雨，比赛也照常进行。","py":"jíshǐ xià yǔ, bǐsài yě zhàocháng jìnxíng.","ja":"설령 비가 와도, 시합은 예정대로 진행돼요.","hsk":4},
{"zh":"即使再难，我也要完成。","py":"jíshǐ zài nán, wǒ yě yào wánchéng.","ja":"설령 아무리 어려워도, 저는 끝까지 해낼 거예요.","hsk":4},
{"zh":"即便他不同意，我也要做。","py":"jíbiàn tā bù tóngyì, wǒ yě yào zuò.","ja":"그가 반대해도, 저는 할 거예요.","hsk":4},
{"zh":"即便失败了，也不要灰心。","py":"jíbiàn shībài le, yě bú yào huīxīn.","ja":"설령 실패해도, 낙심하지 마세요.","hsk":4},
{"zh":"就算你不说，我也知道。","py":"jiùsuàn nǐ bù shuō, wǒ yě zhīdào.","ja":"당신이 말하지 않아도, 저는 알아요.","hsk":4},
{"zh":"就算再忙，也要按时吃饭。","py":"jiùsuàn zài máng, yě yào ànshí chīfàn.","ja":"아무리 바빠도, 제때 밥을 먹어야 해요.","hsk":4},
{"zh":"哪怕只有一点希望，也要尝试。","py":"nǎpà zhǐyǒu yìdiǎn xīwàng, yě yào chángshì.","ja":"조금의 희망이라도 있다면, 시도해 볼 거예요.","hsk":4},
{"zh":"哪怕花再多钱，他也要买那辆车。","py":"nǎpà huā zài duō qián, tā yě yào mǎi nà liàng chē.","ja":"돈이 아무리 들어도, 그는 저 차를 사요.","hsk":4},
{"zh":"既然你来了，就留下来吃饭吧。","py":"jìrán nǐ lái le, jiù liú xiàlái chīfàn ba.","ja":"온 김에, 밥 먹고 가요.","hsk":4},
{"zh":"既然这样，就不要勉强。","py":"jìrán zhèyàng, jiù bú yào miǎnqiǎng.","ja":"그렇다면, 무리하지 마세요.","hsk":4},
{"zh":"既然你不想去，那就别去了。","py":"jìrán nǐ bù xiǎng qù, nà jiù bié qù le.","ja":"가고 싶지 않으면, 안 가도 돼요.","hsk":4},
{"zh":"既然决定了，就好好做。","py":"jìrán juédìng le, jiù hǎohǎo zuò.","ja":"결정했으니, 제대로 하세요.","hsk":4},
{"zh":"既然大家都同意，那就这么办吧。","py":"jìrán dàjiā dōu tóngyì, nà jiù zhème bàn ba.","ja":"다들 찬성하니, 그렇게 합시다.","hsk":4},
{"zh":"既然你已经知道了，我就不多说了。","py":"jìrán nǐ yǐjīng zhīdào le, wǒ jiù bù duō shuō le.","ja":"이미 알고 있으니, 더 말하지 않을게요.","hsk":4},
{"zh":"一旦决定，就不能后悔。","py":"yídàn juédìng, jiù bù néng hòuhuǐ.","ja":"일단 결정하면, 후회할 수 없어요.","hsk":4},
{"zh":"一旦发生问题，请立刻通知我。","py":"yídàn fāshēng wèntí, qǐng lìkè tōngzhī wǒ.","ja":"문제가 생기면, 즉시 저에게 알려 주세요.","hsk":4},
{"zh":"一旦养成习惯，就很难改变。","py":"yídàn yǎngchéng xíguàn, jiù hěn nán gǎibiàn.","ja":"일단 습관이 들면, 바꾸기 어려워요.","hsk":4},
{"zh":"机会一旦错过，就不会再来。","py":"jīhuì yídàn cuòguò, jiù bú huì zài lái.","ja":"기회는 한번 놓치면, 다시 오지 않아요.","hsk":4},
{"zh":"这道题不管我怎么想，都想不出答案。","py":"zhè dào tí bùguǎn wǒ zěnme xiǎng, dōu xiǎng bu chū dáàn.","ja":"이 문제는 아무리 생각해도 답이 안 나와요.","hsk":4},
{"zh":"无论什么时候，你都可以来找我。","py":"wúlùn shénme shíhou, nǐ dōu kěyǐ lái zhǎo wǒ.","ja":"언제든지, 저를 찾아와도 돼요.","hsk":4},
{"zh":"不管去哪里，他都带着这本书。","py":"bùguǎn qù nǎlǐ, tā dōu dài zhe zhè běn shū.","ja":"어디를 가든, 그는 이 책을 가지고 다녀요.","hsk":4},
{"zh":"不管你来不来，我都会等你。","py":"bùguǎn nǐ lái bu lái, wǒ dōu huì děng nǐ.","ja":"당신이 오든 안 오든, 저는 기다릴게요.","hsk":4},
{"zh":"无论你愿不愿意，这都是你的责任。","py":"wúlùn nǐ yuàn bu yuànyì, zhè dōu shì nǐ de zérèn.","ja":"당신이 원하든 원치 않든, 이건 당신 책임이에요.","hsk":4},
{"zh":"即使全世界都反对，我也支持你。","py":"jíshǐ quán shìjiè dōu fǎnduì, wǒ yě zhīchí nǐ.","ja":"설령 온 세상이 반대해도, 저는 당신을 지지해요.","hsk":4},
{"zh":"哪怕再晚，我也会等你回来。","py":"nǎpà zài wǎn, wǒ yě huì děng nǐ huílái.","ja":"아무리 늦어도, 저는 당신이 돌아오길 기다릴게요.","hsk":4},
{"zh":"既然如此，我们就开始吧。","py":"jìrán rúcǐ, wǒmen jiù kāishǐ ba.","ja":"그렇다면, 우리 시작합시다.","hsk":4},
{"zh":"无论如何，我都要把这件事做完。","py":"wúlùn rúhé, wǒ dōu yào bǎ zhè jiàn shì zuò wán.","ja":"무슨 일이 있어도, 이 일을 끝낼 거예요.","hsk":4},
{"zh":"一旦下定决心，他就不会改变。","py":"yídàn xià dìng juéxīn, tā jiù bú huì gǎibiàn.","ja":"일단 결심하면, 그는 바꾸지 않아요.","hsk":4},
{"zh":"不管怎么样，谢谢你的帮助。","py":"bùguǎn zěnmeyàng, xièxie nǐ de bāngzhù.","ja":"어쨌든, 도와줘서 고마워요.","hsk":4},
{"zh":"他不仅会说中文，还会说日语。","py":"tā bùjǐn huì shuō Zhōngwén, hái huì shuō Rìyǔ.","ja":"그는 중국어뿐 아니라, 일본어도 할 줄 알아요.","hsk":4},
{"zh":"他不但聪明，而且很努力。","py":"tā búdàn cōngming, érqiě hěn nǔlì.","ja":"그는 똑똑할 뿐 아니라, 노력파이기도 해요.","hsk":4},
{"zh":"这家餐厅不仅好吃，而且便宜。","py":"zhè jiā cāntīng bùjǐn hǎochī, érqiě piányi.","ja":"이 식당은 맛있을 뿐 아니라, 싸요.","hsk":4},
{"zh":"她不但会唱歌，还会跳舞。","py":"tā búdàn huì chàng gē, hái huì tiàowǔ.","ja":"그녀는 노래할 줄 알 뿐 아니라, 춤도 출 줄 알아요.","hsk":4},
{"zh":"运动不仅对身体好，也能放松心情。","py":"yùndòng bùjǐn duì shēntǐ hǎo, yě néng fàngsōng xīnqíng.","ja":"운동은 몸에 좋을 뿐 아니라, 기분도 풀어 줘요.","hsk":4},
{"zh":"他不仅没生气，反而笑了。","py":"tā bùjǐn méi shēngqì, fǎn'ér xiào le.","ja":"그는 화내기는커녕, 오히려 웃었어요.","hsk":4},
{"zh":"不仅如此，他还获得了奖学金。","py":"bùjǐn rúcǐ, tā hái huòdé le jiǎngxuéjīn.","ja":"그뿐 아니라, 그는 장학금도 받았어요.","hsk":4},
{"zh":"除非你道歉，否则我不原谅你。","py":"chúfēi nǐ dàoqiàn, fǒuzé wǒ bù yuánliàng nǐ.","ja":"사과하지 않는 한, 용서하지 않아요.","hsk":4},
{"zh":"除非下大雨，否则比赛照常进行。","py":"chúfēi xià dà yǔ, fǒuzé bǐsài zhàocháng jìnxíng.","ja":"큰비가 오지 않는 한, 시합은 예정대로 진행돼요.","hsk":4},
{"zh":"除非你亲自去，否则解决不了。","py":"chúfēi nǐ qīnzì qù, fǒuzé jiějué bu liǎo.","ja":"당신이 직접 가지 않는 한, 해결할 수 없어요.","hsk":4},
{"zh":"除非努力学习，才能通过考试。","py":"chúfēi nǔlì xuéxí, cái néng tōngguò kǎoshì.","ja":"열심히 공부해야만, 시험에 합격할 수 있어요.","hsk":4},
{"zh":"这件事除非他同意，否则没办法做。","py":"zhè jiàn shì chúfēi tā tóngyì, fǒuzé méi bànfǎ zuò.","ja":"이 일은 그가 동의하지 않는 한, 할 방법이 없어요.","hsk":4},
{"zh":"只有亲眼看到，才会相信。","py":"zhǐyǒu qīnyǎn kàndào, cái huì xiāngxìn.","ja":"직접 눈으로 봐야만, 믿을 수 있어요.","hsk":4},
{"zh":"只有多练习，才能说好中文。","py":"zhǐyǒu duō liànxí, cái néng shuō hǎo Zhōngwén.","ja":"많이 연습해야만, 중국어를 잘할 수 있어요.","hsk":4},
{"zh":"只要有时间，我就会去。","py":"zhǐyào yǒu shíjiān, wǒ jiù huì qù.","ja":"시간만 있으면, 저는 갈 거예요.","hsk":4},
{"zh":"与其抱怨，不如行动。","py":"yǔqí bàoyuàn, bùrú xíngdòng.","ja":"불평하느니, 차라리 행동하자.","hsk":4},
{"zh":"与其在家等，不如出去找。","py":"yǔqí zài jiā děng, bùrú chūqù zhǎo.","ja":"집에서 기다리느니, 나가서 찾는 게 나아요.","hsk":4},
{"zh":"与其买新的，不如修旧的。","py":"yǔqí mǎi xīn de, bùrú xiū jiù de.","ja":"새것을 사느니, 헌것을 고치는 게 나아요.","hsk":4},
{"zh":"宁可走路，也不坐他的车。","py":"nìngkě zǒulù, yě bú zuò tā de chē.","ja":"차라리 걷지, 그의 차는 안 타요.","hsk":4},
{"zh":"我宁愿自己做，也不想麻烦别人。","py":"wǒ nìngyuàn zìjǐ zuò, yě bù xiǎng máfan biérén.","ja":"저는 차라리 혼자 하지, 남에게 폐 끼치고 싶지 않아요.","hsk":4},
{"zh":"他宁可饿着，也不吃剩饭。","py":"tā nìngkě è zhe, yě bù chī shèngfàn.","ja":"그는 차라리 굶을지언정, 남은 음식은 안 먹어요.","hsk":4},
{"zh":"不是不愿意，而是没时间。","py":"bú shì bú yuànyì, ér shì méi shíjiān.","ja":"하기 싫은 게 아니라, 시간이 없는 거예요.","hsk":4},
{"zh":"这不是钱的问题，而是态度的问题。","py":"zhè bú shì qián de wèntí, ér shì tàidu de wèntí.","ja":"이건 돈 문제가 아니라, 태도 문제예요.","hsk":4},
{"zh":"错的不是你，而是我。","py":"cuò de bú shì nǐ, ér shì wǒ.","ja":"틀린 건 당신이 아니라, 저예요.","hsk":4},
{"zh":"他每天不是看书，就是写文章。","py":"tā měitiān bú shì kàn shū, jiù shì xiě wénzhāng.","ja":"그는 매일, 책을 읽거나 글을 써요.","hsk":4},
{"zh":"周末他不是在家，就是在图书馆。","py":"zhōumò tā bú shì zài jiā, jiù shì zài túshūguǎn.","ja":"주말에 그는 집에 있거나 도서관에 있어요.","hsk":4},
{"zh":"之所以失败，是因为没有努力。","py":"zhīsuǒyǐ shībài, shì yīnwèi méiyǒu nǔlì.","ja":"실패한 것은, 노력하지 않았기 때문이에요.","hsk":4},
{"zh":"我之所以迟到，是因为堵车了。","py":"wǒ zhīsuǒyǐ chídào, shì yīnwèi dǔchē le.","ja":"제가 지각한 것은, 차가 막혔기 때문이에요.","hsk":4},
{"zh":"他之所以成功，是因为坚持。","py":"tā zhīsuǒyǐ chénggōng, shì yīnwèi jiānchí.","ja":"그가 성공한 것은, 꾸준히 했기 때문이에요.","hsk":4},
{"zh":"之所以选择这里，是因为离家近。","py":"zhīsuǒyǐ xuǎnzé zhèlǐ, shì yīnwèi lí jiā jìn.","ja":"여기를 고른 것은, 집에서 가깝기 때문이에요.","hsk":4},
{"zh":"通过努力，他终于实现了梦想。","py":"tōngguò nǔlì, tā zhōngyú shíxiàn le mèngxiǎng.","ja":"노력을 통해, 그는 마침내 꿈을 이뤘어요.","hsk":4},
{"zh":"经过几年的努力，他成了专家。","py":"jīngguò jǐ nián de nǔlì, tā chéng le zhuānjiā.","ja":"몇 년의 노력을 거쳐, 그는 전문가가 됐어요.","hsk":4},
{"zh":"通过这件事，我学到了很多。","py":"tōngguò zhè jiàn shì, wǒ xué dào le hěn duō.","ja":"이 일을 통해, 저는 많은 것을 배웠어요.","hsk":4},
{"zh":"他靠自己的努力买了房子。","py":"tā kào zìjǐ de nǔlì mǎi le fángzi.","ja":"그는 자기 노력으로 집을 샀어요.","hsk":4},
{"zh":"不仅孩子喜欢，大人也喜欢。","py":"bùjǐn háizi xǐhuan, dàren yě xǐhuan.","ja":"아이뿐 아니라, 어른도 좋아해요.","hsk":4},
{"zh":"这个方法既简单又有效。","py":"zhège fāngfǎ jì jiǎndān yòu yǒuxiào.","ja":"이 방법은 간단한 데다 효과적이에요.","hsk":4},
{"zh":"他既是老师，也是作家。","py":"tā jì shì lǎoshī, yě shì zuòjiā.","ja":"그는 교사이기도 하고, 작가이기도 해요.","hsk":4},
{"zh":"学习外语既要努力，也要方法。","py":"xuéxí wàiyǔ jì yào nǔlì, yě yào fāngfǎ.","ja":"외국어 학습은 노력도 방법도 필요해요.","hsk":4},
{"zh":"与其说他聪明，不如说他努力。","py":"yǔqí shuō tā cōngming, bùrú shuō tā nǔlì.","ja":"그는 똑똑하다기보다, 노력파라고 하는 게 맞아요.","hsk":4},
{"zh":"由于天气不好，飞机晚点了。","py":"yóuyú tiānqì bù hǎo, fēijī wǎndiǎn le.","ja":"날씨가 안 좋아서, 비행기가 연착했어요.","hsk":4},
{"zh":"由于交通堵塞，我迟到了。","py":"yóuyú jiāotōng dǔsè, wǒ chídào le.","ja":"교통 체증 때문에, 지각했어요.","hsk":4},
{"zh":"由于工作原因，他不能参加。","py":"yóuyú gōngzuò yuányīn, tā bù néng cānjiā.","ja":"업무 사정으로, 그는 참가할 수 없어요.","hsk":4},
{"zh":"由于准备充分，考试很顺利。","py":"yóuyú zhǔnbèi chōngfèn, kǎoshì hěn shùnlì.","ja":"준비가 충분해서, 시험이 순조로웠어요.","hsk":4},
{"zh":"因此，我们应该早点出发。","py":"yīncǐ, wǒmen yīnggāi zǎo diǎn chūfā.","ja":"그러니, 일찍 출발하는 게 좋아요.","hsk":4},
{"zh":"他很努力，因此取得了好成绩。","py":"tā hěn nǔlì, yīncǐ qǔdé le hǎo chéngjì.","ja":"그는 노력파라서, 좋은 성적을 거뒀어요.","hsk":4},
{"zh":"路上堵车，于是我们改坐地铁。","py":"lùshang dǔchē, yúshì wǒmen gǎi zuò dìtiě.","ja":"길이 막혀서, 우리는 지하철로 바꿨어요.","hsk":4},
{"zh":"这个方法成本太高，因而没被采用。","py":"zhège fāngfǎ chéngběn tài gāo, yīn'ér méi bèi cǎiyòng.","ja":"이 방법은 비용이 너무 높아서, 채택되지 않았어요.","hsk":4},
{"zh":"这个问题恐怕不容易解决。","py":"zhège wèntí kǒngpà bù róngyì jiějué.","ja":"이 문제는 해결하기 쉽지 않을 것 같아요.","hsk":4},
{"zh":"恐怕来不及了，快点吧。","py":"kǒngpà lái bu jí le, kuài diǎn ba.","ja":"아마 못 맞출 거예요, 서두르자.","hsk":4},
{"zh":"这么晚了，他恐怕不会来了。","py":"zhème wǎn le, tā kǒngpà bú huì lái le.","ja":"이렇게 늦었으니, 그는 아마 안 올 거예요.","hsk":4},
{"zh":"估计他不会来了。","py":"gūjì tā bú huì lái le.","ja":"아마 그는 안 올 거예요.","hsk":4},
{"zh":"看来今天要下雨。","py":"kànlái jīntiān yào xià yǔ.","ja":"보아하니, 오늘 비가 올 것 같아요.","hsk":4},
{"zh":"估计这件事还得几天。","py":"gūjì zhè jiàn shì hái děi jǐ tiān.","ja":"이 일은 며칠 더 걸릴 것 같아요.","hsk":4},
{"zh":"他可能已经知道了。","py":"tā kěnéng yǐjīng zhīdào le.","ja":"그는 이미 알고 있을지도 몰라요.","hsk":4},
{"zh":"说不定他还在等我们。","py":"shuōbudìng tā hái zài děng wǒmen.","ja":"어쩌면 그는 아직 우리를 기다리고 있을지도 몰라요.","hsk":4},
{"zh":"据说他要辞职了。","py":"jùshuō tā yào cízhí le.","ja":"그는 사직할 거래요.","hsk":4},
{"zh":"听说那家公司倒闭了。","py":"tīngshuō nà jiā gōngsī dǎobì le.","ja":"그 회사는 도산했대요.","hsk":4},
{"zh":"据报道，明天有台风。","py":"jù bàodào, míngtiān yǒu táifēng.","ja":"보도에 따르면, 내일 태풍이 와요.","hsk":4},
{"zh":"据我所知，他还没结婚。","py":"jù wǒ suǒ zhī, tā hái méi jiéhūn.","ja":"제가 아는 한, 그는 아직 결혼하지 않았어요.","hsk":4},
{"zh":"这是因为我忘了带钥匙。","py":"zhè shì yīnwèi wǒ wàng le dài yàoshi.","ja":"열쇠 가져오는 걸 잊어버렸기 때문이에요.","hsk":4},
{"zh":"他迟到，是因为路上堵车。","py":"tā chídào, shì yīnwèi lùshang dǔchē.","ja":"그가 지각한 것은, 길이 막혔기 때문이에요.","hsk":4},
{"zh":"就是因为太粗心，他才出了错。","py":"jiù shì yīnwèi tài cūxīn, tā cái chū le cuò.","ja":"너무 부주의했기 때문에, 그는 실수를 했어요.","hsk":4},
{"zh":"多亏了你的帮助，我才能成功。","py":"duōkuī le nǐ de bāngzhù, wǒ cái néng chénggōng.","ja":"당신 도움 덕분에, 성공할 수 있었어요.","hsk":4},
{"zh":"幸亏你提醒我，不然就忘了。","py":"xìngkuī nǐ tíxǐng wǒ, bùrán jiù wàng le.","ja":"당신이 일깨워 준 덕분에, 잊지 않았어요.","hsk":4},
{"zh":"幸好带了伞，要不然就淋湿了。","py":"xìnghǎo dài le sǎn, yàobùrán jiù lín shī le.","ja":"우산을 가져와서 다행이지, 안 그랬으면 젖을 뻔했어요.","hsk":4},
{"zh":"多亏有你在，问题很快解决了。","py":"duōkuī yǒu nǐ zài, wèntí hěn kuài jiějué le.","ja":"당신이 있어 준 덕분에, 문제가 금방 해결됐어요.","hsk":4},
{"zh":"正因为他懒，所以才失败。","py":"zhèng yīnwèi tā lǎn, suǒyǐ cái shībài.","ja":"그는 게을렀기 때문에 바로 실패했어요.","hsk":4},
{"zh":"正因为难，才更要努力。","py":"zhèng yīnwèi nán, cái gèng yào nǔlì.","ja":"어렵기 때문에 더욱 노력해야 해요.","hsk":4},
{"zh":"因为身体的关系，他提前退休了。","py":"yīnwèi shēntǐ de guānxi, tā tíqián tuìxiū le.","ja":"몸 사정으로, 그는 일찍 퇴직했어요.","hsk":4},
{"zh":"怪不得这么冷，原来下雪了。","py":"guàibude zhème lěng, yuánlái xià xuě le.","ja":"어쩐지 이렇게 춥더라, 알고 보니 눈이 왔구나.","hsk":4},
{"zh":"难怪他不高兴，原来被批评了。","py":"nánguài tā bù gāoxìng, yuánlái bèi pīpíng le.","ja":"어쩐지 그가 기분이 안 좋더라, 알고 보니 혼났구나.","hsk":4},
{"zh":"怪不得找不到，原来放错地方了。","py":"guàibude zhǎo bu dào, yuánlái fàng cuò dìfang le.","ja":"어쩐지 안 보이더라, 알고 보니 둘 곳을 잘못 뒀구나.","hsk":4},
{"zh":"因为下雨，所以比赛取消了。","py":"yīnwèi xià yǔ, suǒyǐ bǐsài qǔxiāo le.","ja":"비가 와서, 시합이 취소됐어요.","hsk":4},
{"zh":"由此可见，努力很重要。","py":"yóucǐ kějiàn, nǔlì hěn zhòngyào.","ja":"이로써, 노력이 중요하다는 것을 알 수 있어요.","hsk":4},
{"zh":"他病了，所以没来上课。","py":"tā bìng le, suǒyǐ méi lái shàngkè.","ja":"그는 아파서, 수업에 오지 않았어요.","hsk":4},
{"zh":"出于安全考虑，这里禁止吸烟。","py":"chūyú ānquán kǎolǜ, zhèlǐ jìnzhǐ xīyān.","ja":"안전상의 이유로, 여기는 금연입니다.","hsk":4},
{"zh":"他出于好意，提醒了你。","py":"tā chūyú hǎoyì, tíxǐng le nǐ.","ja":"그는 호의에서, 당신에게 일깨워 준 거예요.","hsk":4},
{"zh":"为了健康，他每天跑步。","py":"wèile jiànkāng, tā měitiān pǎobù.","ja":"건강을 위해, 그는 매일 달려요.","hsk":4},
{"zh":"看来他不会来了。","py":"kànlái tā bú huì lái le.","ja":"아무래도 그는 안 올 것 같아요.","hsk":4},
{"zh":"他似乎不太高兴。","py":"tā sìhū bú tài gāoxìng.","ja":"그는 별로 기분이 안 좋은 것 같아요.","hsk":4},
{"zh":"天好像要下雨了。","py":"tiān hǎoxiàng yào xià yǔ le.","ja":"하늘이 곧 비가 올 것 같아요.","hsk":4},
{"zh":"他看上去比实际年龄年轻。","py":"tā kàn shàngqù bǐ shíjì niánlíng niánqīng.","ja":"그는 실제 나이보다 젊어 보여요.","hsk":4},
{"zh":"这件事似乎没那么简单。","py":"zhè jiàn shì sìhū méi nàme jiǎndān.","ja":"이 일은 그렇게 간단하지 않은 것 같아요.","hsk":4},
{"zh":"听起来很有道理。","py":"tīng qǐlái hěn yǒu dàoli.","ja":"들어 보니, 일리가 있네요.","hsk":4},
{"zh":"这道菜看起来很好吃。","py":"zhè dào cài kàn qǐlái hěn hǎochī.","ja":"이 요리는 맛있어 보여요.","hsk":4},
{"zh":"这个问题说起来容易，做起来难。","py":"zhège wèntí shuō qǐlái róngyì, zuò qǐlái nán.","ja":"이 문제는 말하기는 쉽지만, 하기는 어려워요.","hsk":4},
{"zh":"这件衣服穿起来很舒服。","py":"zhè jiàn yīfu chuān qǐlái hěn shūfu.","ja":"이 옷은 입어 보면 편해요.","hsk":4},
{"zh":"这种手机用起来很方便。","py":"zhè zhǒng shǒujī yòng qǐlái hěn fāngbiàn.","ja":"이런 휴대폰은 써 보면 편리해요.","hsk":4},
{"zh":"他今天显得特别精神。","py":"tā jīntiān xiǎnde tèbié jīngshen.","ja":"그는 오늘 유난히 활기차 보여요.","hsk":4},
{"zh":"这次旅行给我留下了深刻的印象。","py":"zhè cì lǚxíng gěi wǒ liú xià le shēnkè de yìnxiàng.","ja":"이번 여행은 깊은 인상을 남겼어요.","hsk":4},
{"zh":"他给我的第一印象很好。","py":"tā gěi wǒ de dì yī yìnxiàng hěn hǎo.","ja":"그의 첫인상은 아주 좋았어요.","hsk":4},
{"zh":"这部电影值得一看。","py":"zhè bù diànyǐng zhíde yí kàn.","ja":"이 영화는 한번 볼 가치가 있어요.","hsk":4},
{"zh":"这个地方值得一去。","py":"zhège dìfang zhíde yí qù.","ja":"이곳은 한번 가 볼 가치가 있어요.","hsk":4},
{"zh":"他的精神值得我们学习。","py":"tā de jīngshen zhíde wǒmen xuéxí.","ja":"그의 정신은 우리가 본받을 가치가 있어요.","hsk":4},
{"zh":"我觉得这个想法不错。","py":"wǒ juéde zhège xiǎngfǎ búcuò.","ja":"저는 이 아이디어가 괜찮은 것 같아요.","hsk":4},
{"zh":"我认为这个计划可行。","py":"wǒ rènwéi zhège jìhuà kěxíng.","ja":"저는 이 계획이 실행 가능하다고 생각해요.","hsk":4},
{"zh":"我以为今天是星期六。","py":"wǒ yǐwéi jīntiān shì xīngqīliù.","ja":"저는 오늘이 토요일인 줄 알았어요.","hsk":4},
{"zh":"大家都觉得这个主意很好。","py":"dàjiā dōu juéde zhège zhǔyi hěn hǎo.","ja":"다들 이 아이디어가 좋다고 생각해요.","hsk":4},
{"zh":"在我看来，他是对的。","py":"zài wǒ kàn lái, tā shì duì de.","ja":"제가 보기엔, 그가 옳아요.","hsk":4},
{"zh":"对我来说，健康最重要。","py":"duì wǒ lái shuō, jiànkāng zuì zhòngyào.","ja":"저에게는, 건강이 가장 중요해요.","hsk":4},
{"zh":"依我看，这件事还得再商量。","py":"yī wǒ kàn, zhè jiàn shì hái děi zài shāngliang.","ja":"제가 보기엔, 이 일은 다시 의논해야 해요.","hsk":4},
{"zh":"在很多人看来，钱就是一切。","py":"zài hěn duō rén kàn lái, qián jiù shì yíqiè.","ja":"많은 사람이 보기엔, 돈이 전부예요.","hsk":4},
{"zh":"这件事对我影响很大。","py":"zhè jiàn shì duì wǒ yǐngxiǎng hěn dà.","ja":"이 일은 저에게 큰 영향을 줬어요.","hsk":4},
{"zh":"吸烟对身体有害。","py":"xīyān duì shēntǐ yǒuhài.","ja":"흡연은 몸에 해로워요.","hsk":4},
{"zh":"这个决定对公司很重要。","py":"zhège juédìng duì gōngsī hěn zhòngyào.","ja":"이 결정은 회사에 중요해요.","hsk":4},
{"zh":"这本书让人深思。","py":"zhè běn shū ràng rén shēnsī.","ja":"이 책은 사람을 깊이 생각하게 해요.","hsk":4},
{"zh":"这个消息让人很失望。","py":"zhège xiāoxi ràng rén hěn shīwàng.","ja":"이 소식은 사람을 아주 실망시켜요.","hsk":4},
{"zh":"他的表演让人印象深刻。","py":"tā de biǎoyǎn ràng rén yìnxiàng shēnkè.","ja":"그의 연기는 사람에게 깊은 인상을 줘요.","hsk":4},
{"zh":"这部电影使人感动。","py":"zhè bù diànyǐng shǐ rén gǎndòng.","ja":"이 영화는 사람을 감동시켜요.","hsk":4},
{"zh":"听说他下个月就要结婚了。","py":"tīngshuō tā xià ge yuè jiù yào jiéhūn le.","ja":"듣자 하니, 그는 다음 달에 곧 결혼한대요.","hsk":4},
{"zh":"火车快要开了，我们快走吧。","py":"huǒchē kuài yào kāi le, wǒmen kuài zǒu ba.","ja":"기차가 곧 출발해요, 서두릅시다.","hsk":4},
{"zh":"天快要黑了。","py":"tiān kuài yào hēi le.","ja":"곧 어두워져요.","hsk":4},
{"zh":"听说这家店的菜很地道。","py":"tīngshuō zhè jiā diàn de cài hěn dìdao.","ja":"이 집 요리는 본고장 맛이래요.","hsk":4},
{"zh":"据说这本书很受欢迎。","py":"jùshuō zhè běn shū hěn shòu huānyíng.","ja":"이 책은 아주 인기가 있대요.","hsk":4},
{"zh":"看样子今天是来不了了。","py":"kàn yàngzi jīntiān shì lái bu liǎo le.","ja":"보아하니, 오늘은 못 올 것 같아요.","hsk":4},
{"zh":"我好像在哪里见过你。","py":"wǒ hǎoxiàng zài nǎlǐ jiàn guò nǐ.","ja":"저는 어디선가 당신을 본 적이 있는 것 같아요.","hsk":4},
{"zh":"这首歌给人一种温暖的感觉。","py":"zhè shǒu gē gěi rén yì zhǒng wēnnuǎn de gǎnjué.","ja":"이 노래는 따뜻한 느낌을 줘요.","hsk":4},
{"zh":"听他这么一说，我才明白。","py":"tīng tā zhème yì shuō, wǒ cái míngbai.","ja":"그가 그렇게 말하는 걸 듣고, 비로소 알았어요.","hsk":4},
{"zh":"这个孩子真聪明！","py":"zhège háizi zhēn cōngming!","ja":"이 아이는 정말 똑똑해!","hsk":4},
{"zh":"今天太热了！","py":"jīntiān tài rè le!","ja":"오늘은 너무 더워!","hsk":4},
{"zh":"这里的风景多美啊！","py":"zhèlǐ de fēngjǐng duō měi a!","ja":"여기 경치는 얼마나 아름다운지!","hsk":4},
{"zh":"这部电影真感人！","py":"zhè bù diànyǐng zhēn gǎnrén!","ja":"이 영화는 정말 감동적이야!","hsk":4},
{"zh":"你怎么才来啊！","py":"nǐ zěnme cái lái a!","ja":"왜 이제야 오는 거야!","hsk":4},
{"zh":"这道题太难了，我做不出来。","py":"zhè dào tí tài nán le, wǒ zuò bu chūlái.","ja":"이 문제는 너무 어려워서, 못 풀겠어요.","hsk":4},
{"zh":"你看，多漂亮的花啊！","py":"nǐ kàn, duō piàoliang de huā a!","ja":"봐, 얼마나 예쁜 꽃이야!","hsk":4},
{"zh":"今天热死了。","py":"jīntiān rè sǐ le.","ja":"오늘은 더워 죽겠어요.","hsk":4},
{"zh":"这个菜好吃极了。","py":"zhège cài hǎochī jí le.","ja":"이 요리는 더없이 맛있어요.","hsk":4},
{"zh":"我最近忙得很。","py":"wǒ zuìjìn máng de hěn.","ja":"저는 요즘 무척 바빠요.","hsk":4},
{"zh":"听到这个消息，我高兴坏了。","py":"tīng dào zhège xiāoxi, wǒ gāoxìng huài le.","ja":"이 소식을 듣고, 저는 너무 기뻤어요.","hsk":4},
{"zh":"这件事把我累坏了。","py":"zhè jiàn shì bǎ wǒ lèi huài le.","ja":"이 일로 저는 녹초가 됐어요.","hsk":4},
{"zh":"他居然没来！","py":"tā jūrán méi lái!","ja":"뜻밖에 그는 안 왔어요!","hsk":4},
{"zh":"没想到他竟然成功了。","py":"méi xiǎngdào tā jìngrán chénggōng le.","ja":"그가 성공할 줄은 생각도 못 했어요.","hsk":4},
{"zh":"这么简单的题，他竟然做错了。","py":"zhème jiǎndān de tí, tā jìngrán zuò cuò le.","ja":"이렇게 쉬운 문제를, 그가 뜻밖에 틀렸어요.","hsk":4},
{"zh":"我简直不敢相信。","py":"wǒ jiǎnzhí bù gǎn xiāngxìn.","ja":"저는 도무지 믿을 수가 없어요.","hsk":4},
{"zh":"这里简直就是天堂。","py":"zhèlǐ jiǎnzhí jiù shì tiāntáng.","ja":"여기는 그야말로 천국이에요.","hsk":4},
{"zh":"他的中文好得简直像母语。","py":"tā de Zhōngwén hǎo de jiǎnzhí xiàng mǔyǔ.","ja":"그의 중국어는 마치 모국어처럼 능숙해요.","hsk":4},
{"zh":"难道你忘了吗？","py":"nándào nǐ wàng le ma?","ja":"설마 잊은 거예요?","hsk":4},
{"zh":"难道这不是真的吗？","py":"nándào zhè bú shì zhēn de ma?","ja":"설마 이게 사실이 아니라는 거예요?","hsk":4},
{"zh":"难道你不想去吗？","py":"nándào nǐ bù xiǎng qù ma?","ja":"설마 가고 싶지 않다는 거예요?","hsk":4},
{"zh":"你到底想说什么？","py":"nǐ dàodǐ xiǎng shuō shénme?","ja":"당신은 도대체 무슨 말이 하고 싶은 거예요?","hsk":4},
{"zh":"这究竟是怎么回事？","py":"zhè jiūjìng shì zěnme huí shì?","ja":"이게 도대체 어떻게 된 일이에요?","hsk":4},
{"zh":"你到底去不去？","py":"nǐ dàodǐ qù bu qù?","ja":"당신은 결국 갈 거예요 말 거예요?","hsk":4},
{"zh":"反正没人知道。","py":"fǎnzhèng méi rén zhīdào.","ja":"어차피 아무도 몰라요.","hsk":4},
{"zh":"你别劝我了，反正我不去。","py":"nǐ bié quàn wǒ le, fǎnzhèng wǒ bú qù.","ja":"설득하지 마요, 어차피 저는 안 가요.","hsk":4},
{"zh":"他偏偏没去。","py":"tā piānpiān méi qù.","ja":"그는 하필 가지 않았어요.","hsk":4},
{"zh":"我要出门，偏偏下起了大雨。","py":"wǒ yào chūmén, piānpiān xià qǐ le dà yǔ.","ja":"나가려는데, 하필 큰비가 내리기 시작했어요.","hsk":4},
{"zh":"你千万别迟到。","py":"nǐ qiānwàn bié chídào.","ja":"절대 지각하지 마세요.","hsk":4},
{"zh":"路上千万要小心。","py":"lùshang qiānwàn yào xiǎoxīn.","ja":"가는 길에 부디 조심하세요.","hsk":4},
{"zh":"这件事你千万不要告诉别人。","py":"zhè jiàn shì nǐ qiānwàn bú yào gàosu biérén.","ja":"이 일은 절대 남에게 말하지 마세요.","hsk":4},
{"zh":"我巴不得马上回家。","py":"wǒ bābude mǎshàng huí jiā.","ja":"당장이라도 집에 가고 싶어요.","hsk":4},
{"zh":"他巴不得你快点走。","py":"tā bābude nǐ kuài diǎn zǒu.","ja":"그는 당신이 빨리 가 줬으면 해서 안달이에요.","hsk":4},
{"zh":"我恨不得一口气把它做完。","py":"wǒ hènbude yìkǒuqì bǎ tā zuò wán.","ja":"저는 한 번에 그걸 끝내 버리고 싶어요.","hsk":4},
{"zh":"累得我恨不得马上睡觉。","py":"lèi de wǒ hènbude mǎshàng shuìjiào.","ja":"너무 피곤해서, 당장 자 버리고 싶어요.","hsk":4},
{"zh":"早知道就不去了。","py":"zǎo zhīdào jiù bú qù le.","ja":"알았더라면 안 갔을 텐데.","hsk":4},
{"zh":"早知道下雨，就带伞了。","py":"zǎo zhīdào xià yǔ, jiù dài sǎn le.","ja":"비 올 줄 알았으면, 우산을 가져왔을 텐데.","hsk":4},
{"zh":"他怎么会这样？","py":"tā zěnme huì zhèyàng?","ja":"그는 어째서 그럴까요?","hsk":4},
{"zh":"你怎么会不知道？","py":"nǐ zěnme huì bù zhīdào?","ja":"어떻게 모를 수가 있어요?","hsk":4},
{"zh":"难得你来一次，多坐一会儿吧。","py":"nándé nǐ lái yí cì, duō zuò yíhuìr ba.","ja":"모처럼 한 번 왔으니, 좀 더 앉았다 가요.","hsk":4},
{"zh":"大家难得聚在一起，好好聊聊吧。","py":"dàjiā nándé jù zài yìqǐ, hǎohǎo liáoliao ba.","ja":"다들 좀처럼 모이기 힘드니, 천천히 이야기 나눠요.","hsk":4},
{"zh":"我的钱包被偷了。","py":"wǒ de qiánbāo bèi tōu le.","ja":"지갑을 도둑맞았어요.","hsk":4},
{"zh":"他被老师批评了。","py":"tā bèi lǎoshī pīpíng le.","ja":"그는 선생님께 혼났어요.","hsk":4},
{"zh":"我的自行车被人骑走了。","py":"wǒ de zìxíngchē bèi rén qí zǒu le.","ja":"제 자전거를 누군가 타고 가 버렸어요.","hsk":4},
{"zh":"那本书被借走了。","py":"nà běn shū bèi jiè zǒu le.","ja":"그 책은 누가 빌려 가 버렸어요.","hsk":4},
{"zh":"蛋糕被弟弟吃光了。","py":"dàngāo bèi dìdi chī guāng le.","ja":"케이크는 남동생이 다 먹어 치웠어요.","hsk":4},
{"zh":"这个问题终于被解决了。","py":"zhège wèntí zhōngyú bèi jiějué le.","ja":"이 문제는 마침내 해결됐어요.","hsk":4},
{"zh":"我的手机叫小偷偷走了。","py":"wǒ de shǒujī jiào xiǎotōu tōu zǒu le.","ja":"제 휴대폰을 도둑이 훔쳐 갔어요.","hsk":4},
{"zh":"杯子让他打破了。","py":"bēizi ràng tā dǎ pò le.","ja":"컵이 그에게 깨졌어요.","hsk":4},
{"zh":"我的伞让人拿错了。","py":"wǒ de sǎn ràng rén ná cuò le.","ja":"제 우산을 누가 잘못 가져갔어요.","hsk":4},
{"zh":"钱包给人偷了。","py":"qiánbāo gěi rén tōu le.","ja":"지갑을 누군가에게 도둑맞았어요.","hsk":4},
{"zh":"他受到了大家的尊敬。","py":"tā shòudào le dàjiā de zūnjìng.","ja":"그는 모두에게 존경받았어요.","hsk":4},
{"zh":"这部电影受到了观众的欢迎。","py":"zhè bù diànyǐng shòudào le guānzhòng de huānyíng.","ja":"이 영화는 관객에게 환영받았어요.","hsk":4},
{"zh":"他的努力得到了认可。","py":"tā de nǔlì dédào le rènkě.","ja":"그의 노력은 인정받았어요.","hsk":4},
{"zh":"这个建议受到了重视。","py":"zhège jiànyì shòudào le zhòngshì.","ja":"이 제안은 중시되었어요.","hsk":4},
{"zh":"这本书是他写的。","py":"zhè běn shū shì tā xiě de.","ja":"이 책은 그가 쓴 거예요.","hsk":4},
{"zh":"我是昨天来的。","py":"wǒ shì zuótiān lái de.","ja":"저는 어제 온 거예요.","hsk":4},
{"zh":"这件衣服是在北京买的。","py":"zhè jiàn yīfu shì zài Běijīng mǎi de.","ja":"이 옷은 베이징에서 산 거예요.","hsk":4},
{"zh":"这个蛋糕是妈妈做的。","py":"zhège dàngāo shì māma zuò de.","ja":"이 케이크는 엄마가 만든 거예요.","hsk":4},
{"zh":"这是由专家决定的。","py":"zhè shì yóu zhuānjiā juédìng de.","ja":"이것은 전문가가 결정한 거예요.","hsk":4},
{"zh":"这件事由我负责。","py":"zhè jiàn shì yóu wǒ fùzé.","ja":"이 일은 제가 책임집니다.","hsk":4},
{"zh":"会议由王经理主持。","py":"huìyì yóu Wáng jīnglǐ zhǔchí.","ja":"회의는 왕 매니저가 진행해요.","hsk":4},
{"zh":"关于这件事，我有不同的看法。","py":"guānyú zhè jiàn shì, wǒ yǒu bùtóng de kànfǎ.","ja":"이 일에 관해, 저는 다른 의견이 있어요.","hsk":4},
{"zh":"对于这个问题，大家意见不一致。","py":"duìyú zhège wèntí, dàjiā yìjiàn bù yízhì.","ja":"이 문제에 대해, 다들 의견이 일치하지 않아요.","hsk":4},
{"zh":"至于价格，我们可以商量。","py":"zhìyú jiàgé, wǒmen kěyǐ shāngliang.","ja":"가격에 관해서는, 우리가 상의할 수 있어요.","hsk":4},
{"zh":"关于这次旅行，我已经做好了计划。","py":"guānyú zhè cì lǚxíng, wǒ yǐjīng zuò hǎo le jìhuà.","ja":"이번 여행에 관해서는, 이미 계획을 다 세웠어요.","hsk":4},
{"zh":"至于结果，现在还不好说。","py":"zhìyú jiéguǒ, xiànzài hái bù hǎo shuō.","ja":"결과에 관해서는, 지금은 아직 뭐라 말하기 어려워요.","hsk":4},
{"zh":"对孩子来说，父母的爱很重要。","py":"duì háizi lái shuō, fùmǔ de ài hěn zhòngyào.","ja":"아이에게는, 부모의 사랑이 중요해요.","hsk":4},
{"zh":"对他而言，这只是一份工作。","py":"duì tā ér yán, zhè zhǐ shì yí fèn gōngzuò.","ja":"그에게는, 이건 그저 하나의 일에 불과해요.","hsk":4},
{"zh":"这个问题与我无关。","py":"zhège wèntí yǔ wǒ wú guān.","ja":"이 문제는 저와 관계없어요.","hsk":4},
{"zh":"这件事跟你没关系。","py":"zhè jiàn shì gēn nǐ méi guānxi.","ja":"이 일은 당신과 관계없어요.","hsk":4},
{"zh":"健康与饮食密切相关。","py":"jiànkāng yǔ yǐnshí mìqiè xiāngguān.","ja":"건강은 식생활과 밀접하게 관련돼 있어요.","hsk":4},
{"zh":"据我所知，他没去过中国。","py":"jù wǒ suǒ zhī, tā méi qù guo Zhōngguó.","ja":"제가 아는 한, 그는 중국에 가 본 적이 없어요.","hsk":4},
{"zh":"据了解，这家公司经营得很好。","py":"jù liǎojiě, zhè jiā gōngsī jīngyíng de hěn hǎo.","ja":"알려진 바로는, 이 회사는 경영이 잘되고 있어요.","hsk":4},
{"zh":"在这种情况下，我也没办法。","py":"zài zhè zhǒng qíngkuàng xià, wǒ yě méi bànfǎ.","ja":"이런 상황에서는, 저도 어쩔 도리가 없어요.","hsk":4},
{"zh":"在大家的帮助下，我完成了任务。","py":"zài dàjiā de bāngzhù xià, wǒ wánchéng le rènwu.","ja":"모두의 도움으로, 저는 임무를 완수했어요.","hsk":4},
{"zh":"在老师的指导下，他进步很快。","py":"zài lǎoshī de zhǐdǎo xià, tā jìnbù hěn kuài.","ja":"선생님의 지도 아래, 그의 실력은 빨리 늘어요.","hsk":4},
{"zh":"在任何情况下，都不能放弃。","py":"zài rènhé qíngkuàng xià, dōu bù néng fàngqì.","ja":"어떤 상황에서도, 포기해서는 안 돼요.","hsk":4},
{"zh":"随着时间的推移，他慢慢好起来了。","py":"suízhe shíjiān de tuīyí, tā mànmàn hǎo qǐlái le.","ja":"시간이 지남에 따라, 그는 점차 회복됐어요.","hsk":4},
{"zh":"随着年龄的增长，他越来越成熟。","py":"suízhe niánlíng de zēngzhǎng, tā yuè lái yuè chéngshú.","ja":"나이가 들수록, 그는 점점 성숙해졌어요.","hsk":4},
{"zh":"在他的帮助下，我完成了任务。","py":"zài tā de bāngzhù xià, wǒ wánchéng le rènwu.","ja":"그의 도움 덕분에, 저는 임무를 완수했어요.","hsk":4},
{"zh":"这次比上次好得多。","py":"zhè cì bǐ shàng cì hǎo de duō.","ja":"이번에는 지난번보다 훨씬 좋았어요.","hsk":4},
{"zh":"今天比昨天冷多了。","py":"jīntiān bǐ zuótiān lěng duō le.","ja":"오늘은 어제보다 훨씬 추워요.","hsk":4},
{"zh":"这条裤子比那条长一点。","py":"zhè tiáo kùzi bǐ nà tiáo cháng yìdiǎn.","ja":"이 바지는 저 바지보다 조금 길어요.","hsk":4},
{"zh":"这个房间比那个大一些。","py":"zhège fángjiān bǐ nàge dà yìxiē.","ja":"이 방은 저 방보다 조금 넓어요.","hsk":4},
{"zh":"他比我高五厘米。","py":"tā bǐ wǒ gāo wǔ límǐ.","ja":"그는 저보다 5센티 커요.","hsk":4},
{"zh":"这件比那件便宜二十块。","py":"zhè jiàn bǐ nà jiàn piányi èrshí kuài.","ja":"이건 저것보다 20위안 싸요.","hsk":4},
{"zh":"他比我更努力。","py":"tā bǐ wǒ gèng nǔlì.","ja":"그는 저보다 더 노력해요.","hsk":4},
{"zh":"今天比昨天还热。","py":"jīntiān bǐ zuótiān hái rè.","ja":"오늘은 어제보다 더 더워요.","hsk":4},
{"zh":"这个办法比那个更好。","py":"zhège bànfǎ bǐ nàge gèng hǎo.","ja":"이 방법은 저 방법보다 더 좋아요.","hsk":4},
{"zh":"我没有他高。","py":"wǒ méi yǒu tā gāo.","ja":"저는 그만큼 키가 크지 않아요.","hsk":4},
{"zh":"这家店没有那家有名。","py":"zhè jiā diàn méi yǒu nà jiā yǒumíng.","ja":"이 가게는 저 가게만큼 유명하지 않아요.","hsk":4},
{"zh":"我的中文没有你说得好。","py":"wǒ de Zhōngwén méi yǒu nǐ shuō de hǎo.","ja":"제 중국어는 당신만큼 잘하지 못해요.","hsk":4},
{"zh":"他不如我聪明。","py":"tā bùrú wǒ cōngming.","ja":"그는 저만큼 똑똑하지 않아요.","hsk":4},
{"zh":"坐车不如走路快。","py":"zuò chē bùrú zǒulù kuài.","ja":"차를 타느니 걷는 게 빨라요.","hsk":4},
{"zh":"这家餐厅不如以前了。","py":"zhè jiā cāntīng bùrú yǐqián le.","ja":"이 식당은 예전만 못해졌어요.","hsk":4},
{"zh":"谁都比不上他认真。","py":"shéi dōu bǐ bú shàng tā rènzhēn.","ja":"아무도 그만큼 성실하지 않아요.","hsk":4},
{"zh":"这个跟那个一样好。","py":"zhège gēn nàge yíyàng hǎo.","ja":"이건 저것과 똑같이 좋아요.","hsk":4},
{"zh":"我跟他差不多大。","py":"wǒ gēn tā chàbuduō dà.","ja":"저는 그와 나이가 거의 같아요.","hsk":4},
{"zh":"这两件衣服的价钱差不多。","py":"zhè liǎng jiàn yīfu de jiàqian chàbuduō.","ja":"이 옷 두 벌의 가격은 거의 같아요.","hsk":4},
{"zh":"他的水平跟我差不多。","py":"tā de shuǐpíng gēn wǒ chàbuduō.","ja":"그의 수준은 저와 거의 같아요.","hsk":4},
{"zh":"这本书比那本贵两倍。","py":"zhè běn shū bǐ nà běn guì liǎng bèi.","ja":"이 책은 저 책의 2배 비싸요.","hsk":4},
{"zh":"这个城市的人口是那个的三倍。","py":"zhège chéngshì de rénkǒu shì nàge de sān bèi.","ja":"이 도시의 인구는 저 도시의 3배예요.","hsk":4},
{"zh":"今年的收入比去年增加了一倍。","py":"jīnnián de shōurù bǐ qùnián zēngjiā le yí bèi.","ja":"올해 수입은 작년보다 두 배로 늘었어요.","hsk":4},
{"zh":"没有什么比健康更重要。","py":"méi yǒu shénme bǐ jiànkāng gèng zhòngyào.","ja":"건강만큼 중요한 것은 없어요.","hsk":4},
{"zh":"这是我看过最好的电影。","py":"zhè shì wǒ kàn guo zuì hǎo de diànyǐng.","ja":"이건 제가 본 영화 중 가장 좋은 영화예요.","hsk":4},
{"zh":"他是班里最高的学生。","py":"tā shì bān li zuì gāo de xuésheng.","ja":"그는 반에서 키가 가장 큰 학생이에요.","hsk":4},
{"zh":"没有谁比他更了解这件事。","py":"méi yǒu shéi bǐ tā gèng liǎojiě zhè jiàn shì.","ja":"이 일을 그만큼 잘 아는 사람은 없어요.","hsk":4},
{"zh":"越来越多的人开始学中文。","py":"yuè lái yuè duō de rén kāishǐ xué Zhōngwén.","ja":"중국어를 배우는 사람이 점점 늘고 있어요.","hsk":4},
{"zh":"天气越来越冷了。","py":"tiānqì yuè lái yuè lěng le.","ja":"날씨가 점점 추워져요.","hsk":4},
{"zh":"价格越来越高了。","py":"jiàgé yuè lái yuè gāo le.","ja":"가격이 점점 비싸졌어요.","hsk":4},
{"zh":"跟去年相比，今年的成绩好多了。","py":"gēn qùnián xiāngbǐ, jīnnián de chéngjì hǎo duō le.","ja":"작년과 비교하면, 올해 성적이 훨씬 좋아요.","hsk":4},
{"zh":"比起坐飞机，我更喜欢坐火车。","py":"bǐ qǐ zuò fēijī, wǒ gèng xǐhuan zuò huǒchē.","ja":"비행기보다, 저는 기차 타는 걸 더 좋아해요.","hsk":4},
{"zh":"跟大城市相比，这里的生活更安静。","py":"gēn dà chéngshì xiāngbǐ, zhèlǐ de shēnghuó gèng ānjìng.","ja":"대도시와 비교하면, 이곳 생활이 더 조용해요.","hsk":4},
{"zh":"钱不是越多越好。","py":"qián bú shì yuè duō yuè hǎo.","ja":"돈은 많을수록 좋은 게 아니에요.","hsk":4},
{"zh":"这个消息再好不过了。","py":"zhège xiāoxi zài hǎo bú guò le.","ja":"이 소식은 더없이 좋아요.","hsk":4},
{"zh":"他对工作极其认真。","py":"tā duì gōngzuò jíqí rènzhēn.","ja":"그는 일에 대해 극히 성실해요.","hsk":4},
{"zh":"这部电影好看得不得了。","py":"zhè bù diànyǐng hǎokàn de bùdéliǎo.","ja":"이 영화는 엄청나게 재미있어요.","hsk":4},
{"zh":"他汉语说得相当流利。","py":"tā Hànyǔ shuō de xiāngdāng liúlì.","ja":"그는 중국어를 상당히 유창하게 말해요.","hsk":4},
{"zh":"这个箱子我拿不动。","py":"zhège xiāngzi wǒ ná bu dòng.","ja":"이 상자는 들어 올릴 수 없어요.","hsk":4},
{"zh":"我太累了，走不动了。","py":"wǒ tài lèi le, zǒu bu dòng le.","ja":"너무 피곤해서, 더는 못 걷겠어요.","hsk":4},
{"zh":"这么多饭，我吃不了。","py":"zhème duō fàn, wǒ chī bu liǎo.","ja":"이렇게 많은 밥, 다 못 먹어요.","hsk":4},
{"zh":"这个房间住不下十个人。","py":"zhège fángjiān zhù bu xià shí ge rén.","ja":"이 방에는 열 명이 못 묵어요.","hsk":4},
{"zh":"这个箱子太小，装不下这些书。","py":"zhège xiāngzi tài xiǎo, zhuāng bu xià zhèxiē shū.","ja":"이 상자는 너무 작아서, 이 책들이 안 들어가요.","hsk":4},
{"zh":"这个字我看不清楚。","py":"zhège zì wǒ kàn bu qīngchu.","ja":"이 글자는 또렷이 안 보여요.","hsk":4},
{"zh":"你说得太小声，我听不清楚。","py":"nǐ shuō de tài xiǎoshēng, wǒ tīng bu qīngchu.","ja":"목소리가 너무 작아서, 또렷이 안 들려요.","hsk":4},
{"zh":"太远了，我看不见。","py":"tài yuǎn le, wǒ kàn bu jiàn.","ja":"너무 멀어서, 안 보여요.","hsk":4},
{"zh":"这件事我办不到。","py":"zhè jiàn shì wǒ bàn bu dào.","ja":"이 일은 저로서는 못 해요.","hsk":4},
{"zh":"这种东西现在买不到。","py":"zhè zhǒng dōngxi xiànzài mǎi bu dào.","ja":"이런 물건은 지금은 구할 수 없어요.","hsk":4},
{"zh":"我真没想到会这样。","py":"wǒ zhēn méi xiǎngdào huì zhèyàng.","ja":"정말 이렇게 될 줄은 생각도 못 했어요.","hsk":4},
{"zh":"他说得太快，我听不懂。","py":"tā shuō de tài kuài, wǒ tīng bu dǒng.","ja":"그는 말이 너무 빨라서, 못 알아들어요.","hsk":4},
{"zh":"这篇文章太难，我看不懂。","py":"zhè piān wénzhāng tài nán, wǒ kàn bu dǒng.","ja":"이 글은 너무 어려워서, 읽어도 모르겠어요.","hsk":4},
{"zh":"这么多东西，吃得完吗？","py":"zhème duō dōngxi, chī de wán ma?","ja":"이렇게 많이, 다 먹을 수 있어요?","hsk":4},
{"zh":"作业太多，今天做不完。","py":"zuòyè tài duō, jīntiān zuò bu wán.","ja":"숙제가 너무 많아서, 오늘은 다 못 끝내요.","hsk":4},
{"zh":"快点，要不然赶不上火车了。","py":"kuài diǎn, yàobùrán gǎn bu shàng huǒchē le.","ja":"서둘러요, 안 그러면 기차를 놓쳐요.","hsk":4},
{"zh":"这双鞋我穿不上。","py":"zhè shuāng xié wǒ chuān bu shàng.","ja":"이 신발은 (작아서) 못 신어요.","hsk":4},
{"zh":"这里太热了，我受不了。","py":"zhèlǐ tài rè le, wǒ shòu bu liǎo.","ja":"여기는 너무 더워서, 못 견디겠어요.","hsk":4},
{"zh":"时间来不及了，我们打车吧。","py":"shíjiān lái bu jí le, wǒmen dǎchē ba.","ja":"시간이 안 돼요, 택시 탑시다.","hsk":4},
{"zh":"这个消息让人忘不了。","py":"zhège xiāoxi ràng rén wàng bu liǎo.","ja":"이 소식은 잊을 수가 없어요.","hsk":4},
{"zh":"他高兴得笑了起来。","py":"tā gāoxìng de xiào le qǐlái.","ja":"그는 기뻐서, 웃기 시작했어요.","hsk":4},
{"zh":"听到这个消息，大家都欢呼起来。","py":"tīng dào zhège xiāoxi, dàjiā dōu huānhū qǐlái.","ja":"이 소식을 듣고, 다들 환호하기 시작했어요.","hsk":4},
{"zh":"突然下起雨来了。","py":"tūrán xià qǐ yǔ lái le.","ja":"갑자기 비가 내리기 시작했어요.","hsk":4},
{"zh":"孩子一看见妈妈就哭了起来。","py":"háizi yí kànjiàn māma jiù kū le qǐlái.","ja":"아이는 엄마를 보자마자 울기 시작했어요.","hsk":4},
{"zh":"我想起来了，他叫小王。","py":"wǒ xiǎng qǐlái le, tā jiào Xiǎo Wáng.","ja":"생각났어요, 그는 왕 씨예요.","hsk":4},
{"zh":"我想出来一个好办法。","py":"wǒ xiǎng chūlái yí ge hǎo bànfǎ.","ja":"저는 좋은 방법을 생각해 냈어요.","hsk":4},
{"zh":"我一眼就认出来了他。","py":"wǒ yìyǎn jiù rèn chūlái le tā.","ja":"저는 한눈에 그를 알아봤어요.","hsk":4},
{"zh":"我看出来你有心事。","py":"wǒ kàn chūlái nǐ yǒu xīnshì.","ja":"당신이 걱정거리가 있다는 걸 알아챘어요.","hsk":4},
{"zh":"他坚持下去了。","py":"tā jiānchí xiàqù le.","ja":"그는 계속 버텼어요.","hsk":4},
{"zh":"请你继续说下去。","py":"qǐng nǐ jìxù shuō xiàqù.","ja":"이어서 계속 말씀하세요.","hsk":4},
{"zh":"无论多难，都要活下去。","py":"wúlùn duō nán, dōu yào huó xiàqù.","ja":"아무리 힘들어도, 계속 살아가야 해요.","hsk":4},
{"zh":"这本书太无聊，我读不下去了。","py":"zhè běn shū tài wúliáo, wǒ dú bu xiàqù le.","ja":"이 책은 너무 지루해서, 더는 못 읽겠어요.","hsk":4},
{"zh":"这件事说起来容易，做起来难。","py":"zhè jiàn shì shuō qǐlái róngyì, zuò qǐlái nán.","ja":"이 일은 말하기는 쉽지만, 하기는 어려워요.","hsk":4},
{"zh":"这个菜看起来很好吃。","py":"zhège cài kàn qǐlái hěn hǎochī.","ja":"이 요리는 맛있어 보여요.","hsk":4},
{"zh":"他听到名字，转过头来。","py":"tā tīng dào míngzi, zhuǎn guò tóu lái.","ja":"그는 이름을 듣고, 이쪽으로 고개를 돌렸어요.","hsk":4},
{"zh":"请把重点记下来。","py":"qǐng bǎ zhòngdiǎn jì xiàlái.","ja":"요점을 적어 두세요.","hsk":4},
{"zh":"车慢慢停了下来。","py":"chē mànmàn tíng le xiàlái.","ja":"차가 천천히 멈췄어요.","hsk":4},
{"zh":"我尝出来这里面放了糖。","py":"wǒ cháng chūlái zhè lǐmiàn fàng le táng.","ja":"저는 이 안에 설탕이 든 걸 맛으로 알아챘어요.","hsk":4},
{"zh":"随着年龄的增长，我越来越喜欢安静。","py":"suízhe niánlíng de zēngzhǎng, wǒ yuè lái yuè xǐhuan ānjìng.","ja":"나이가 들수록, 저는 점점 조용한 것을 좋아하게 됐어요.","hsk":4},
{"zh":"随着科技的发展，生活越来越方便。","py":"suízhe kējì de fāzhǎn, shēnghuó yuè lái yuè fāngbiàn.","ja":"기술의 발전에 따라, 생활이 점점 편리해지고 있어요.","hsk":4},
{"zh":"随着经济的发展，人们的生活水平提高了。","py":"suízhe jīngjì de fāzhǎn, rénmen de shēnghuó shuǐpíng tígāo le.","ja":"경제 발전에 따라, 사람들의 생활 수준이 높아졌어요.","hsk":4},
{"zh":"凡是参加比赛的人，都有奖品。","py":"fánshì cānjiā bǐsài de rén, dōu yǒu jiǎngpǐn.","ja":"시합에 참가한 사람에게는, 모두 경품이 있어요.","hsk":4},
{"zh":"凡是来过这里的人，都说好。","py":"fánshì lái guo zhèlǐ de rén, dōu shuō hǎo.","ja":"여기에 와 본 사람은, 모두 좋다고 해요.","hsk":4},
{"zh":"任何事情都有两面性。","py":"rènhé shìqing dōu yǒu liǎng miàn xìng.","ja":"어떤 일에도 양면성이 있어요.","hsk":4},
{"zh":"任何人都不能违反规定。","py":"rènhé rén dōu bù néng wéifǎn guīdìng.","ja":"어떤 사람도 규정을 위반해서는 안 돼요.","hsk":4},
{"zh":"对于这个问题，专家有不同的看法。","py":"duìyú zhège wèntí, zhuānjiā yǒu bùtóng de kànfǎ.","ja":"이 문제에 대해, 전문가는 다른 견해가 있어요.","hsk":4},
{"zh":"关于环保，我们还有很多工作要做。","py":"guānyú huánbǎo, wǒmen hái yǒu hěn duō gōngzuò yào zuò.","ja":"환경 보호에 관해, 우리에겐 아직 할 일이 많아요.","hsk":4},
{"zh":"至于细节，我们以后再讨论。","py":"zhìyú xìjié, wǒmen yǐhòu zài tǎolùn.","ja":"세부 사항에 관해서는, 나중에 의논합시다.","hsk":4},
{"zh":"通过这次经验，我学到了很多。","py":"tōngguò zhè cì jīngyàn, wǒ xué dào le hěn duō.","ja":"이번 경험을 통해, 저는 많은 것을 배웠어요.","hsk":4},
{"zh":"由于工作原因，我经常出差。","py":"yóuyú gōngzuò yuányīn, wǒ jīngcháng chūchāi.","ja":"업무 사정으로, 저는 자주 출장을 가요.","hsk":4},
{"zh":"在这种情况下，我们应该冷静。","py":"zài zhè zhǒng qíngkuàng xià, wǒmen yīnggāi lěngjìng.","ja":"이런 상황에서, 우리는 냉정해야 해요.","hsk":4},
{"zh":"在他的影响下，我开始喜欢音乐。","py":"zài tā de yǐngxiǎng xià, wǒ kāishǐ xǐhuan yīnyuè.","ja":"그의 영향을 받아, 저는 음악을 좋아하게 됐어요.","hsk":4},
{"zh":"从某种意义上说，他是对的。","py":"cóng mǒu zhǒng yìyì shàng shuō, tā shì duì de.","ja":"어떤 의미에서는, 그가 옳아요.","hsk":4},
{"zh":"从这个角度来看，这个计划是可行的。","py":"cóng zhège jiǎodù lái kàn, zhège jìhuà shì kěxíng de.","ja":"이 각도에서 보면, 이 계획은 실행 가능해요.","hsk":4},
{"zh":"从长远来看，这是一个好决定。","py":"cóng chángyuǎn lái kàn, zhè shì yí ge hǎo juédìng.","ja":"길게 보면, 이건 좋은 결정이에요.","hsk":4},
{"zh":"从表面上看，他很冷静。","py":"cóng biǎomiàn shàng kàn, tā hěn lěngjìng.","ja":"겉으로는, 그는 아주 냉정해요.","hsk":4},
{"zh":"从整体上来说，这次活动很成功。","py":"cóng zhěngtǐ shàng lái shuō, zhè cì huódòng hěn chénggōng.","ja":"전체적으로 말하면, 이번 행사는 성공적이었어요.","hsk":4},
{"zh":"在学习方面，他非常努力。","py":"zài xuéxí fāngmiàn, tā fēicháng nǔlì.","ja":"공부 면에서, 그는 매우 열심이에요.","hsk":4},
{"zh":"在某种程度上，这也是一种进步。","py":"zài mǒu zhǒng chéngdù shàng, zhè yě shì yì zhǒng jìnbù.","ja":"어느 정도, 이것도 일종의 진보예요.","hsk":4},
{"zh":"他在工作方面很有经验。","py":"tā zài gōngzuò fāngmiàn hěn yǒu jīngyàn.","ja":"그는 업무 면에서 경험이 풍부해요.","hsk":4},
{"zh":"我一有时间就去看你。","py":"wǒ yì yǒu shíjiān jiù qù kàn nǐ.","ja":"저는 시간이 나면 바로 당신을 만나러 갈게요.","hsk":4},
{"zh":"只有亲身经历，才能真正理解。","py":"zhǐyǒu qīnshēn jīnglì, cái néng zhēnzhèng lǐjiě.","ja":"직접 겪어 봐야만, 진정으로 이해할 수 있어요.","hsk":4},
{"zh":"一旦决定，就不要轻易改变。","py":"yídàn juédìng, jiù bú yào qīngyì gǎibiàn.","ja":"일단 결정하면, 함부로 바꾸면 안 돼요.","hsk":4},
{"zh":"只要有信心，什么困难都能克服。","py":"zhǐyào yǒu xìnxīn, shénme kùnnan dōu néng kèfú.","ja":"자신감만 있으면, 어떤 어려움도 극복할 수 있어요.","hsk":4},
{"zh":"万一下雨，我们就改天去。","py":"wànyī xià yǔ, wǒmen jiù gǎitiān qù.","ja":"만일 비가 오면, 우리 날을 바꿔서 가요.","hsk":4},
{"zh":"假如我是你，我会答应。","py":"jiǎrú wǒ shì nǐ, wǒ huì dāying.","ja":"만약 제가 당신이라면, 승낙할 거예요.","hsk":4},
{"zh":"倘若有问题，请随时联系我。","py":"tǎngruò yǒu wèntí, qǐng suíshí liánxì wǒ.","ja":"만약 문제가 있으면, 언제든지 연락 주세요.","hsk":4},
{"zh":"万一他不来，怎么办？","py":"wànyī tā bù lái, zěnme bàn?","ja":"만일 그가 안 오면, 어떻게 하죠?","hsk":4},
{"zh":"无论遇到什么困难，我们都要面对。","py":"wúlùn yùdào shénme kùnnan, wǒmen dōu yào miànduì.","ja":"어떤 어려움을 만나도, 우리는 맞설 거예요.","hsk":4},
{"zh":"不管结果如何，我都会尽力。","py":"bùguǎn jiéguǒ rúhé, wǒ dōu huì jìnlì.","ja":"결과가 어떻든, 저는 최선을 다할 거예요.","hsk":4},
{"zh":"无论如何，这件事必须今天完成。","py":"wúlùn rúhé, zhè jiàn shì bìxū jīntiān wánchéng.","ja":"무슨 일이 있어도, 이 일은 오늘 안에 끝내야 해요.","hsk":4},
{"zh":"就这件事而言，我同意你的看法。","py":"jiù zhè jiàn shì ér yán, wǒ tóngyì nǐ de kànfǎ.","ja":"이 일에 관해 말하면, 저는 당신 의견에 찬성해요.","hsk":4},
{"zh":"对我而言，家人最重要。","py":"duì wǒ ér yán, jiārén zuì zhòngyào.","ja":"저에게는, 가족이 가장 중요해요.","hsk":4},
{"zh":"关于这次旅行，大家都很期待。","py":"guānyú zhè cì lǚxíng, dàjiā dōu hěn qīdài.","ja":"이번 여행에 관해, 다들 무척 기대하고 있어요.","hsk":4},
{"zh":"总的来说，这次合作很愉快。","py":"zǒng de lái shuō, zhè cì hézuò hěn yúkuài.","ja":"대체로 말하면, 이번 협력은 아주 즐거웠어요.","hsk":4},
{"zh":"换句话说，我们需要更多时间。","py":"huàn jù huà shuō, wǒmen xūyào gèng duō shíjiān.","ja":"바꿔 말하면, 우리에겐 더 많은 시간이 필요해요.","hsk":4},
{"zh":"总之，健康比什么都重要。","py":"zǒngzhī, jiànkāng bǐ shénme dōu zhòngyào.","ja":"요컨대, 건강은 무엇보다 중요해요.","hsk":4},
{"zh":"我先吃饭，然后做作业。","py":"wǒ xiān chī fàn, ránhòu zuò zuòyè.","ja":"먼저 밥을 먹고, 그 다음에 숙제를 해요.","hsk":4},
{"zh":"你先休息一下，然后再出发。","py":"nǐ xiān xiūxi yíxià, ránhòu zài chūfā.","ja":"먼저 좀 쉬고 나서, 출발하자.","hsk":4},
{"zh":"请先填表，再交钱。","py":"qǐng xiān tián biǎo, zài jiāo qián.","ja":"먼저 서류를 작성한 다음, 돈을 내세요.","hsk":4},
{"zh":"首先，我们要明确目标。","py":"shǒuxiān, wǒmen yào míngquè mùbiāo.","ja":"우선, 우리는 목표를 명확히 해야 해요.","hsk":4},
{"zh":"其次，要制定计划。","py":"qícì, yào zhìdìng jìhuà.","ja":"다음으로, 계획을 세워야 해요.","hsk":4},
{"zh":"最后，他终于成功了。","py":"zuìhòu, tā zhōngyú chénggōng le.","ja":"마지막으로, 그는 마침내 성공했어요.","hsk":4},
{"zh":"接着，他又说了几句。","py":"jiēzhe, tā yòu shuō le jǐ jù.","ja":"이어서, 그는 또 몇 마디 했어요.","hsk":4},
{"zh":"他看了我一眼，然后转身走了。","py":"tā kàn le wǒ yìyǎn, ránhòu zhuǎnshēn zǒu le.","ja":"그는 저를 힐끗 보더니, 그 후 돌아서 가 버렸어요.","hsk":4},
{"zh":"灯突然灭了，于是大家都安静下来。","py":"dēng tūrán miè le, yúshì dàjiā dōu ānjìng xiàlái.","ja":"불이 갑자기 꺼지자, 그래서 다들 조용해졌어요.","hsk":4},
{"zh":"起初，我以为他在开玩笑。","py":"qǐchū, wǒ yǐwéi tā zài kāi wánxiào.","ja":"처음에는, 그가 농담하는 줄 알았어요.","hsk":4},
{"zh":"后来，他变得很优秀。","py":"hòulái, tā biàn de hěn yōuxiù.","ja":"나중에, 그는 우수해졌어요.","hsk":4},
{"zh":"一开始，我不太适应。","py":"yì kāishǐ, wǒ bú tài shìyìng.","ja":"처음에는 별로 적응하지 못했어요.","hsk":4},
{"zh":"起初大家都不同意，后来慢慢接受了。","py":"qǐchū dàjiā dōu bù tóngyì, hòulái mànmàn jiēshòu le.","ja":"처음에는 다들 반대했지만, 나중에 점점 받아들였어요.","hsk":4},
{"zh":"来中国之前，我没学过中文。","py":"lái Zhōngguó zhīqián, wǒ méi xué guo Zhōngwén.","ja":"중국에 오기 전, 저는 중국어를 배운 적이 없었어요.","hsk":4},
{"zh":"吃饭之后，我们去散步吧。","py":"chī fàn zhīhòu, wǒmen qù sànbù ba.","ja":"식사 후에, 우리 산책하러 가요.","hsk":4},
{"zh":"毕业以后，他去了上海工作。","py":"bìyè yǐhòu, tā qù le Shànghǎi gōngzuò.","ja":"졸업 후, 그는 상하이로 일하러 갔어요.","hsk":4},
{"zh":"三年以前，这里还是一片农田。","py":"sān nián yǐqián, zhèlǐ hái shì yí piàn nóngtián.","ja":"3년 전, 여기는 아직 온통 농지였어요.","hsk":4},
{"zh":"他一回到家就睡着了。","py":"tā yì huí dào jiā jiù shuìzháo le.","ja":"그는 집에 돌아가자마자 잠들어 버렸어요.","hsk":4},
{"zh":"我刚到家，电话就响了。","py":"wǒ gāng dào jiā, diànhuà jiù xiǎng le.","ja":"제가 막 집에 도착했을 때, 전화가 울렸어요.","hsk":4},
{"zh":"下课铃一响，学生们就跑出去了。","py":"xiàkè líng yì xiǎng, xuéshengmen jiù pǎo chūqù le.","ja":"종이 울리기 무섭게, 학생들이 뛰어나갔어요.","hsk":4},
{"zh":"他刚说完，大家就鼓起掌来。","py":"tā gāng shuō wán, dàjiā jiù gǔ qǐ zhǎng lái.","ja":"그가 말을 마치기 무섭게, 다들 박수를 치기 시작했어요.","hsk":4},
{"zh":"说着说着，他就哭了。","py":"shuōzhe shuōzhe, tā jiù kū le.","ja":"이야기하다 보니, 그는 울어 버렸어요.","hsk":4},
{"zh":"走着走着，天就黑了。","py":"zǒuzhe zǒuzhe, tiān jiù hēi le.","ja":"걷다 보니, 날이 어두워졌어요.","hsk":4},
{"zh":"听着听着，我就睡着了。","py":"tīngzhe tīngzhe, wǒ jiù shuìzháo le.","ja":"듣다 보니, 저는 잠들어 버렸어요.","hsk":4},
{"zh":"从早到晚，他一直在工作。","py":"cóng zǎo dào wǎn, tā yìzhí zài gōngzuò.","ja":"아침부터 저녁까지, 그는 줄곧 일하고 있어요.","hsk":4},
{"zh":"从那以后，我们再也没见过面。","py":"cóng nà yǐhòu, wǒmen zài yě méi jiàn guo miàn.","ja":"그 이후로, 우리는 두 번 다시 만나지 못했어요.","hsk":4},
{"zh":"从明天起，我要早睡早起。","py":"cóng míngtiān qǐ, wǒ yào zǎo shuì zǎo qǐ.","ja":"내일부터, 저는 일찍 자고 일찍 일어날 거예요.","hsk":4},
{"zh":"同时，我也在学习日语。","py":"tóngshí, wǒ yě zài xuéxí Rìyǔ.","ja":"동시에, 저는 일본어도 배우고 있어요.","hsk":4},
{"zh":"此外，他还会弹钢琴。","py":"cǐwài, tā hái huì tán gāngqín.","ja":"그 밖에, 그는 피아노도 칠 수 있어요.","hsk":4},
{"zh":"另外，这件事还需要再考虑。","py":"lìngwài, zhè jiàn shì hái xūyào zài kǎolǜ.","ja":"그리고, 이 일은 좀 더 검토할 필요가 있어요.","hsk":4},
{"zh":"学中文的同时，我也了解了中国文化。","py":"xué Zhōngwén de tóngshí, wǒ yě liǎojiě le Zhōngguó wénhuà.","ja":"중국어를 배우는 동시에, 저는 중국 문화도 이해했어요.","hsk":4},
{"zh":"经过努力，他终于通过了考试。","py":"jīngguò nǔlì, tā zhōngyú tōngguò le kǎoshì.","ja":"노력 끝에, 그는 마침내 시험에 합격했어요.","hsk":4},
{"zh":"天渐渐亮了。","py":"tiān jiànjiàn liàng le.","ja":"하늘이 점점 밝아졌어요.","hsk":4},
{"zh":"他的病逐渐好起来了。","py":"tā de bìng zhújiàn hǎo qǐlái le.","ja":"그의 병은 차츰 나아졌어요.","hsk":4},
{"zh":"他先愣了一下，随后笑了。","py":"tā xiān lèng le yíxià, suíhòu xiào le.","ja":"그는 잠시 멍하더니, 곧 웃었어요.","hsk":4},
{"zh":"紧接着，又发生了一件事。","py":"jǐn jiēzhe, yòu fāshēng le yí jiàn shì.","ja":"곧바로, 또 한 가지 일이 일어났어요.","hsk":4},
{"zh":"到最后，大家都累得不行了。","py":"dào zuìhòu, dàjiā dōu lèi de bùxíng le.","ja":"마지막엔, 다들 녹초가 됐어요.","hsk":4},
{"zh":"过了一会儿，他才慢慢开口。","py":"guò le yíhuìr, tā cái mànmàn kāikǒu.","ja":"잠시 후, 그는 비로소 천천히 입을 열었어요.","hsk":4},
{"zh":"总之，这次旅行很愉快。","py":"zǒngzhī, zhè cì lǚxíng hěn yúkuài.","ja":"요컨대, 이번 여행은 즐거웠어요.","hsk":4},
{"zh":"经过几年的努力，他从一个新人变成了专家。","py":"jīngguò jǐ nián de nǔlì, tā cóng yí ge xīnrén biàn chéng le zhuānjiā.","ja":"몇 년의 노력을 거쳐, 그는 신입에서 전문가가 됐어요.","hsk":4},
{"zh":"我觉得这个菜很好吃。","py":"wǒ juéde zhège cài hěn hǎochī.","ja":"저는 이 요리가 맛있다고 생각해요.","hsk":4},
{"zh":"我感到很幸福。","py":"wǒ gǎn dào hěn xìngfú.","ja":"저는 아주 행복하다고 느껴요.","hsk":4},
{"zh":"我感觉今天有点累。","py":"wǒ gǎnjué jīntiān yǒudiǎn lèi.","ja":"오늘은 조금 피곤한 것 같아요.","hsk":4},
{"zh":"听到这个消息，我感到很意外。","py":"tīng dào zhège xiāoxi, wǒ gǎn dào hěn yìwài.","ja":"이 소식을 듣고, 저는 매우 의외라고 느꼈어요.","hsk":4},
{"zh":"我希望明天天气好。","py":"wǒ xīwàng míngtiān tiānqì hǎo.","ja":"내일 날씨가 좋으면 좋겠어요.","hsk":4},
{"zh":"我盼望着假期的到来。","py":"wǒ pànwàng zhe jiàqī de dàolái.","ja":"저는 휴가가 오기를 손꼽아 기다리고 있어요.","hsk":4},
{"zh":"他渴望得到大家的认可。","py":"tā kěwàng dédào dàjiā de rènkě.","ja":"그는 모두의 인정을 갈망하고 있어요.","hsk":4},
{"zh":"我害怕一个人在家。","py":"wǒ hàipà yí ge rén zài jiā.","ja":"저는 혼자 집에 있는 게 무서워요.","hsk":4},
{"zh":"妈妈很担心我的身体。","py":"māma hěn dānxīn wǒ de shēntǐ.","ja":"엄마는 제 몸을 무척 걱정해요.","hsk":4},
{"zh":"我怕自己做不好。","py":"wǒ pà zìjǐ zuò bu hǎo.","ja":"저는 제가 잘 못할까 봐 걱정이에요.","hsk":4},
{"zh":"你别担心，一切都会好的。","py":"nǐ bié dānxīn, yíqiè dōu huì hǎo de.","ja":"걱정 마요, 다 잘될 거예요.","hsk":4},
{"zh":"他对工作十分认真。","py":"tā duì gōngzuò shífēn rènzhēn.","ja":"그는 일에 아주 성실해요.","hsk":4},
{"zh":"我对结果非常满意。","py":"wǒ duì jiéguǒ fēicháng mǎnyì.","ja":"저는 결과에 매우 만족해요.","hsk":4},
{"zh":"我对历史很感兴趣。","py":"wǒ duì lìshǐ hěn gǎn xìngqù.","ja":"저는 역사에 관심이 많아요.","hsk":4},
{"zh":"他对自己的工作很负责。","py":"tā duì zìjǐ de gōngzuò hěn fùzé.","ja":"그는 자기 일에 책임감이 강해요.","hsk":4},
{"zh":"老师对学生很严格。","py":"lǎoshī duì xuésheng hěn yángé.","ja":"선생님은 학생에게 아주 엄격해요.","hsk":4},
{"zh":"他为这件事感到难过。","py":"tā wèi zhè jiàn shì gǎn dào nánguò.","ja":"그는 이 일로 슬픔을 느꼈어요.","hsk":4},
{"zh":"我为你感到高兴。","py":"wǒ wèi nǐ gǎn dào gāoxìng.","ja":"저는 당신 때문에 기뻐요.","hsk":4},
{"zh":"父母为他感到骄傲。","py":"fùmǔ wèi tā gǎn dào jiāo'ào.","ja":"부모님은 그를 자랑스러워해요.","hsk":4},
{"zh":"我为自己的国家感到自豪。","py":"wǒ wèi zìjǐ de guójiā gǎn dào zìháo.","ja":"저는 제 나라가 자랑스러워요.","hsk":4},
{"zh":"我有点后悔当初的决定。","py":"wǒ yǒudiǎn hòuhuǐ dāngchū de juédìng.","ja":"저는 당초의 결정을 조금 후회해요.","hsk":4},
{"zh":"我很羡慕你能去旅行。","py":"wǒ hěn xiànmù nǐ néng qù lǚxíng.","ja":"저는 당신이 여행을 갈 수 있어서 부러워요.","hsk":4},
{"zh":"别羡慕别人，做好自己。","py":"bié xiànmù biérén, zuò hǎo zìjǐ.","ja":"남을 부러워하지 말고, 자신을 잘 챙기세요.","hsk":4},
{"zh":"他的话让我很感动。","py":"tā de huà ràng wǒ hěn gǎndòng.","ja":"그의 말에 저는 무척 감동했어요.","hsk":4},
{"zh":"这个结果让大家很失望。","py":"zhège jiéguǒ ràng dàjiā hěn shīwàng.","ja":"이 결과에 다들 매우 실망했어요.","hsk":4},
{"zh":"听到这个消息，我非常惊讶。","py":"tīng dào zhège xiāoxi, wǒ fēicháng jīngyà.","ja":"이 소식을 듣고, 저는 무척 놀랐어요.","hsk":4},
{"zh":"见到老朋友，我激动得说不出话。","py":"jiàn dào lǎopéngyou, wǒ jīdòng de shuō bu chū huà.","ja":"옛 친구를 만나, 저는 감격해서 말이 안 나왔어요.","hsk":4},
{"zh":"我很想念家乡的味道。","py":"wǒ hěn xiǎngniàn jiāxiāng de wèidao.","ja":"저는 고향의 맛이 무척 그리워요.","hsk":4},
{"zh":"我很怀念大学时光。","py":"wǒ hěn huáiniàn dàxué shíguāng.","ja":"저는 대학 시절이 무척 그리워요.","hsk":4},
{"zh":"大家都很期待这次旅行。","py":"dàjiā dōu hěn qīdài zhè cì lǚxíng.","ja":"다들 이 여행을 무척 기대하고 있어요.","hsk":4},
{"zh":"我喜欢安静的生活。","py":"wǒ xǐhuan ānjìng de shēnghuó.","ja":"저는 조용한 생활을 좋아해요.","hsk":4},
{"zh":"我最讨厌排队。","py":"wǒ zuì tǎoyàn páiduì.","ja":"저는 줄 서는 걸 가장 싫어해요.","hsk":4},
{"zh":"他对噪音很敏感，受不了吵闹。","py":"tā duì zàoyīn hěn mǐngǎn, shòu bu liǎo chǎonào.","ja":"그는 소음에 민감해서, 시끄러운 걸 못 견뎌요.","hsk":4},
{"zh":"考试之前，我很紧张。","py":"kǎoshì zhīqián, wǒ hěn jǐnzhāng.","ja":"시험 전에, 저는 무척 긴장했어요.","hsk":4},
{"zh":"找不到孩子，妈妈急得不得了。","py":"zhǎo bu dào háizi, māma jí de bùdéliǎo.","ja":"아이를 못 찾아서, 엄마는 몹시 초조했어요.","hsk":4},
{"zh":"你放心吧，我会照顾好他。","py":"nǐ fàngxīn ba, wǒ huì zhàogù hǎo tā.","ja":"안심하세요, 제가 그를 잘 돌볼게요.","hsk":4},
{"zh":"他对未来感到担忧。","py":"tā duì wèilái gǎn dào dānyōu.","ja":"그는 미래에 대해 불안을 느껴요.","hsk":4},
{"zh":"我很感激你的帮助。","py":"wǒ hěn gǎnjī nǐ de bāngzhù.","ja":"당신의 도움에 정말 감사해요.","hsk":4},
{"zh":"如果明天下雨，我就不去了。","py":"rúguǒ míngtiān xià yǔ, wǒ jiù bú qù le.","ja":"만약 내일 비가 오면, 저는 안 갈래요.","hsk":4},
{"zh":"要是你不舒服，就早点休息。","py":"yàoshi nǐ bù shūfu, jiù zǎo diǎn xiūxi.","ja":"몸이 안 좋으면, 일찍 쉬어요.","hsk":4},
{"zh":"如果有问题，可以随时问我。","py":"rúguǒ yǒu wèntí, kěyǐ suíshí wèn wǒ.","ja":"만약 문제가 있으면, 언제든지 물어보세요.","hsk":4},
{"zh":"你要是同意，我们就这么决定。","py":"nǐ yàoshi tóngyì, wǒmen jiù zhème juédìng.","ja":"당신이 찬성하면, 우리 이렇게 정해요.","hsk":4},
{"zh":"有时间的话，我想去旅行。","py":"yǒu shíjiān de huà, wǒ xiǎng qù lǚxíng.","ja":"시간이 있으면, 여행을 가고 싶어요.","hsk":4},
{"zh":"不喜欢的话，可以换一个。","py":"bù xǐhuan de huà, kěyǐ huàn yí ge.","ja":"마음에 안 들면, 바꿀 수 있어요.","hsk":4},
{"zh":"方便的话，请给我回个电话。","py":"fāngbiàn de huà, qǐng gěi wǒ huí ge diànhuà.","ja":"괜찮으시면, 전화 한 통 주세요.","hsk":4},
{"zh":"假如我是你，我就不会这么做。","py":"jiǎrú wǒ shì nǐ, wǒ jiù bú huì zhème zuò.","ja":"만약 제가 당신이라면, 이렇게 하지 않을 거예요.","hsk":4},
{"zh":"倘若有时间，我一定去看你。","py":"tǎngruò yǒu shíjiān, wǒ yídìng qù kàn nǐ.","ja":"만약 시간이 있으면, 꼭 만나러 갈게요.","hsk":4},
{"zh":"假使计划失败，我们也有备用方案。","py":"jiǎshǐ jìhuà shībài, wǒmen yě yǒu bèiyòng fāng'àn.","ja":"설령 계획이 실패해도, 우리에겐 예비안이 있어요.","hsk":4},
{"zh":"万一下雨怎么办？","py":"wànyī xià yǔ zěnme bàn?","ja":"만일 비가 오면 어떡하죠?","hsk":4},
{"zh":"带上伞吧，万一下雨呢。","py":"dài shàng sǎn ba, wànyī xià yǔ ne.","ja":"우산을 가져가자, 만일 비가 오면 안 되니까.","hsk":4},
{"zh":"万一他不同意，我们再想别的办法。","py":"wànyī tā bù tóngyì, wǒmen zài xiǎng bié de bànfǎ.","ja":"만일 그가 동의하지 않으면, 다른 방법을 생각하자.","hsk":4},
{"zh":"多带点钱，以防万一。","py":"duō dài diǎn qián, yǐfáng wànyī.","ja":"만일을 위해, 돈을 넉넉히 가져가요.","hsk":4},
{"zh":"一旦发生问题，立刻通知我。","py":"yídàn fāshēng wèntí, lìkè tōngzhī wǒ.","ja":"문제가 생기면, 즉시 알려 주세요.","hsk":4},
{"zh":"一旦决定了，就别再犹豫。","py":"yídàn juédìng le, jiù bié zài yóuyù.","ja":"일단 정했으면, 더는 망설이지 마.","hsk":4},
{"zh":"机会一旦失去，就很难再有。","py":"jīhuì yídàn shīqù, jiù hěn nán zài yǒu.","ja":"기회는 한번 잃으면, 다시 오기 어려워요.","hsk":4},
{"zh":"即使再忙，也要按时吃饭。","py":"jíshǐ zài máng, yě yào ànshí chī fàn.","ja":"아무리 바빠도, 제때 밥을 먹어야 해요.","hsk":4},
{"zh":"哪怕失败，我也不后悔。","py":"nǎpà shībài, wǒ yě bù hòuhuǐ.","ja":"설령 실패해도, 저는 후회하지 않아요.","hsk":4},
{"zh":"与其在家发呆，不如出去走走。","py":"yǔqí zài jiā fādāi, bùrú chūqù zǒuzou.","ja":"집에서 멍하니 있느니, 나가서 좀 걷는 게 나아요.","hsk":4},
{"zh":"与其等他，不如自己去。","py":"yǔqí děng tā, bùrú zìjǐ qù.","ja":"그를 기다리느니, 직접 가는 게 나아요.","hsk":4},
{"zh":"我宁愿一个人，也不愿将就。","py":"wǒ nìngyuàn yí ge rén, yě bú yuàn jiāngjiu.","ja":"저는 타협할 바엔, 차라리 혼자 있는 게 나아요.","hsk":4},
{"zh":"他宁可加班，也不把工作带回家。","py":"tā nìngkě jiābān, yě bù bǎ gōngzuò dài huí jiā.","ja":"그는 야근할지언정, 일을 집에 가져가지 않아요.","hsk":4},
{"zh":"要不我们去吃饭吧。","py":"yàobu wǒmen qù chī fàn ba.","ja":"그게 아니면, 우리 밥 먹으러 가요.","hsk":4},
{"zh":"快点走，否则就来不及了。","py":"kuài diǎn zǒu, fǒuzé jiù lái bu jí le.","ja":"빨리 가요, 안 그러면 늦어요.","hsk":4},
{"zh":"不然怎么解释呢？","py":"bùrán zěnme jiěshì ne?","ja":"그게 아니면, 어떻게 설명하죠?","hsk":4},
{"zh":"要不然你明天再来吧。","py":"yàobùrán nǐ míngtiān zài lái ba.","ja":"그럼, 내일 다시 와요.","hsk":4},
{"zh":"除非你答应，否则我不走。","py":"chúfēi nǐ dāying, fǒuzé wǒ bù zǒu.","ja":"당신이 승낙하지 않는 한, 저는 안 갈 거예요.","hsk":4},
{"zh":"除非亲眼看到，否则我不相信。","py":"chúfēi qīnyǎn kàndào, fǒuzé wǒ bù xiāngxìn.","ja":"직접 눈으로 보지 않는 한, 저는 안 믿어요.","hsk":4},
{"zh":"这件事除非他同意才行。","py":"zhè jiàn shì chúfēi tā tóngyì cái xíng.","ja":"이 일은 그가 동의해야만 돼요.","hsk":4},
{"zh":"只要努力，就有希望。","py":"zhǐyào nǔlì, jiù yǒu xīwàng.","ja":"노력하기만 하면, 희망이 있어요.","hsk":4},
{"zh":"只有试过，才知道行不行。","py":"zhǐyǒu shì guo, cái zhīdào xíng bu xíng.","ja":"해 봐야만, 되는지 안 되는지 알아요.","hsk":4},
{"zh":"只要你愿意，随时都可以来。","py":"zhǐyào nǐ yuànyì, suíshí dōu kěyǐ lái.","ja":"당신이 원하기만 하면, 언제든지 와도 돼요.","hsk":4},
{"zh":"再难，我也要坚持下去。","py":"zài nán, wǒ yě yào jiānchí xiàqù.","ja":"아무리 어려워도, 저는 계속할 거예요.","hsk":4},
{"zh":"无论如何，我都会支持你。","py":"wúlùn rúhé, wǒ dōu huì zhīchí nǐ.","ja":"무슨 일이 있어도, 저는 당신을 지지해요.","hsk":4},
{"zh":"就算全世界都反对，我也不放弃。","py":"jiùsuàn quán shìjiè dōu fǎnduì, wǒ yě bú fàngqì.","ja":"설령 온 세상이 반대해도, 저는 포기하지 않아요.","hsk":4},
{"zh":"这件事再小，也不能马虎。","py":"zhè jiàn shì zài xiǎo, yě bù néng mǎhu.","ja":"이 일은 아무리 작아도, 소홀히 하면 안 돼요.","hsk":4},
{"zh":"否则就来不及了。","py":"fǒuzé jiù lái bu jí le.","ja":"그렇지 않으면, 늦어요.","hsk":4}
];
